### ISSUE TITLE
開補幀+全螢幕會越來越卡

### ISSUE THREAD

**Issue by liaotaindingdong** [LuckyPuppy514/Play-With-MPV#10]
開補幀+全螢幕會越來越卡，此時display fps estimated值會越來越高，請問該怎麼解?

**Comment by LuckyPuppy514** [comment]
1. 播放器卡顿跟脚本没有什么关系，不太清楚你为啥在这里提issue
2. 卡顿一般看有没有丢帧，Dropped Frames，跟 display fps estimated 没有太大关系
如果你是看了我的博客安装的 mpv-lazy / mpv.net_CM，可以加Q群：921905633 找我，我有空可以远程帮你调试看看

**Comment by liaotaindingdong** [comment]
不好意思，應該問mpv net的! 但想說或許你會剛好知道怎麼解這狀況。

**Comment by liaotaindingdong** [comment]
![image](https://user-images.githubusercontent.com/115889896/195998539-62c0c302-9abc-49e5-ab6b-bd7cf2fbef73.png)

**Comment by LuckyPuppy514** [comment]
卡顿跟硬件也有很大关系，所以怎么解决还要看具体硬件

**Comment by LuckyPuppy514** [comment]
看你的截图，丢帧很严重，肯定是很卡的

**Comment by liaotaindingdong** [comment]
那能否指個路呢?我去看mpv net github disscusion那邊沒看到有人有類似問題，對了我之前用mvp lazy也有這個bug

**Comment by LuckyPuppy514** [comment]
你没有QQ么

**Comment by liaotaindingdong** [comment]
沒..

**Comment by LuckyPuppy514** [comment]
这应该不算bug，要根据硬件做相应的设置，还有可能是你的硬件配置不够

**Comment by liaotaindingdong** [comment]
可是只要不是全螢幕就很順暢。

**Comment by liaotaindingdong** [comment]
![image](https://user-images.githubusercontent.com/115889896/195998744-f37bfc69-1654-4a19-99a0-147d657e8c63.png)

**Comment by LuckyPuppy514** [comment]
那你一般用什么通讯软件，电报？

**Comment by liaotaindingdong** [comment]
也就是這種視窗下就沒問題，而當按下右下角的全螢幕就開始有問題了

**Comment by LuckyPuppy514** [comment]
我这边倒是没遇到过这种问题，最好是能远程上机看看，否则比较难判断什么问题

**Comment by LuckyPuppy514** [comment]
影响卡顿的设置一般是：gpu-context，hwdec，d3d11-adapter，vulkan-device，video-sync

**Comment by liaotaindingdong** [comment]
請問，能抓到低端影視的字幕嗎?
比方說這個:
https://ddys.tv/interstellar/

**Comment by LuckyPuppy514** [comment]
外挂字幕暫時都不支持，而且低端影視的字幕不是通用格式
所以只能自己找字幕了 QAQ

**Comment by liaotaindingdong** [comment]
感謝大神!

**Comment by hooke007** [comment]
从截图来看你可能在执行一个非常离谱的操作，4k渲染下执行60→120FPS的运动补偿，而且源码率异常高。这需要极其变态的硬件才能满足需求

源已经是60fps没有必要补帧
