### ISSUE TITLE
部分视频无法识别

### ISSUE THREAD

**Issue by YURICORN** [LuckyPuppy514/Play-With-MPV#100]
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/43528141/1a46d3c3-f0ed-4287-8816-33d155cb6645)
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/43528141/94534578-8d7e-440c-8325-33088b15cb8b)

**Comment by YURICORN** [comment]
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/43528141/48806e58-f9b1-4251-8cf5-3eb4682f65d7)
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/43528141/3c48b578-1e0e-49f2-9559-5f04eeae1235)

**Comment by LuckyPuppy514** [comment]
某个网站部分视频无法解析是正常的，你说的这个网站更新日志也有说明，仅支持默认线路（VIP 西瓜）

[v3.8.4 新增网站：https://www.agemys.org（仅支持默认线路）](https://github.com/LuckyPuppy514/Play-With-MPV/commit/0840fb927ec93baf0be4caaa2854e9664d29f3f1)
