### ISSUE TITLE
左下圖標擋到特定網頁影片控制鈕

### ISSUE THREAD

**Issue by WeiDerax** [LuckyPuppy514/Play-With-MPV#102]
建議左下控制圖標可以改成自定義位置和可以放大縮小

**Comment by WeiDerax** [comment]
![擷取](https://github.com/LuckyPuppy514/Play-With-MPV/assets/44906201/ca65dcf8-a184-4a17-87e0-bc73540f53ee)

**Comment by LuckyPuppy514** [comment]
自动隐藏也会挡住吗？

**Comment by WeiDerax** [comment]
鼠標不在那位置會隱藏，但移過去就出現，無法點擊到影片控制圖示

**Comment by LuckyPuppy514** [comment]
那暂时在油猴插件中关闭脚本吧，最近没时间改，过段时间才能弄

![20230903212239](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/0376b684-5ec8-41f4-bc30-c0a72f6d75d0)

**Comment by LuckyPuppy514** [comment]
[v3.9.1 新增可拖动功能](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv?version=1254475)
