### ISSUE TITLE
alist挂载阿里云盘后，播放flv格式的视频时，左下角未弹出播放按钮

### ISSUE THREAD

**Issue by Jadaff** [LuckyPuppy514/Play-With-MPV#103]
- 操作系统：windows7 / windows10/11 / ...
- 浏览器：chrome / edge / ...
- 复现问题的操作：alist挂载阿里云盘后，播放flv格式的视频时，左下角未弹出播放按钮。播放mp4和mkv时，是正常弹出的。
- 出现的具体问题：左下角未弹出播放按钮
- 配置截图：建议全屏，或浏览器全屏截图
- 报错截图：
![QQ截图20230903154628](https://github.com/LuckyPuppy514/Play-With-MPV/assets/22736242/fbfb02b5-402b-44ea-af89-35e43adc6cb1)

**Comment by LuckyPuppy514** [comment]
[v3.8.9 已修复](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv?version=1244840)

**Comment by Jadaff** [comment]
> [v3.8.9 已修复](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv?version=1244840)

已经可以了，感谢！
