### ISSUE TITLE
新版的三颗按钮太难看了 

### ISSUE THREAD

**Issue by Sevo7ution** [LuckyPuppy514/Play-With-MPV#104]
新版的三颗按钮太难看了  可以再设置里提供个设置是否开启  不然又丑又挡害  谢谢啦

**Comment by LuckyPuppy514** [comment]
建议暂时在油猴插件中关闭，后续有时间才能修改了

**Comment by LuckyPuppy514** [comment]
[v3.9.1 新增可拖动功能](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv?version=1254475)
