### ISSUE TITLE
网站：https://jojo.bdys.top变更，AList不能播放

### ISSUE THREAD

**Issue by zanewayne78** [LuckyPuppy514/Play-With-MPV#106]
变为`https://jiohub.top`，而且今天我自己改了脚本网址也获取不到播放地址。还有AList（版本3.27） 阿里云盘又不能播放了

**Comment by LuckyPuppy514** [comment]
https://jojo.bdys.top 域名已更新

阿里云盘个人测试没问题，有问题请按模板提供完整信息重新提 issue

![20230918160223](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/8da35d2b-d06e-46e0-989c-8c64fc4b7ab2)

**Comment by zanewayne78** [comment]
我发现了，AList阿里云盘的视频中文标题太长了，标题改短就能播放，有些为了打广告视频标题起的特别长.....

**Comment by LuckyPuppy514** [comment]
标题太长无解，浏览器链接有长度限制，因为传给播放器还需要其他必要参数可能就过长了

**Comment by zanewayne78** [comment]
@LuckyPuppy514 大佬，jojo电视剧可以播放，但是电影分类就不行，F12看链接无效，麻烦大佬修复一下
