### ISSUE TITLE
代理不生效

### ISSUE THREAD

**Issue by cancundeyingzi** [LuckyPuppy514/Play-With-MPV#107]
- 操作系统：windows11 
- 浏览器：edge 
- 网页版ytb秒开,4k流畅
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/73635883/2b957ddc-1136-4730-b144-4cf20e29a88c)

**Comment by LuckyPuppy514** [comment]
请尝试勾选：允许局域网连接

**Comment by cancundeyingzi** [comment]
> 请尝试勾选：允许局域网连接

![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/73635883/1525633d-59d6-4ff4-990b-1d228eb8c0d1)
已重启电脑

**Comment by cancundeyingzi** [comment]
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/73635883/f38cd695-5c0b-4b12-b516-e7ec2e6fc389)


> 请尝试勾选：允许局域网连接

**Comment by LuckyPuppy514** [comment]
打开 F12 控制台，点击播放按钮，把打印的连接复制粘贴上来看看

**Comment by cancundeyingzi** [comment]
mpv://%22https://www.youtube.com/watch?app=desktop&v=T_0lN_-7N5s%22%20--http-proxy=http://127.0.0.1:7890%20--ytdl-raw-options=proxy=[http://127.0.0.1


Launched external handler for 'mpv://%22https://www.youtube.com/watch?app=desktop&v=T_0lN_-7N5s%22%20--http-proxy=http://127.0.0.1:7890%20--ytdl-raw-options=proxy=[http://127.0.0.1:7890]'.

**Comment by cancundeyingzi** [comment]
![【4K HDR】这才是看世界的正确方式！ - YouTube 和另外 4 个页面 - 个人 - Microsoft​ Edge 2023_9_17 18_58_31](https://github.com/LuckyPuppy514/Play-With-MPV/assets/73635883/768df1c3-197b-4862-a050-4a84e3c65a38)

**Comment by LuckyPuppy514** [comment]
脚本没有问题，请检查你的 mpv 安装目录下的 yt-dlp.exe 是不是最新版，自行到 github 下载最新版替换

**Comment by cancundeyingzi** [comment]
已经更新[2023.07.06](https://github.com/yt-dlp/yt-dlp/releases/tag/2023.07.06)
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/73635883/30dd1d2d-6ffb-4e94-9aa3-9b0b8d9af433)

**Comment by LuckyPuppy514** [comment]
打开 cmd，执行以下命令，测试你的代理是否正常

```bat
curl -x http://127.0.0.1:7890 https://www.youtube.com
```

**Comment by cancundeyingzi** [comment]
> 打开 cmd，执行以下命令，测试你的代理是否正常
> 
> ```batchfile
> curl -x http://127.0.0.1:7890 https://www.youtube.com
> ```

可以
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/73635883/a719fc94-7be7-498f-8dc5-ae78193f263e)

**Comment by LuckyPuppy514** [comment]
那这样看来是你的 mpv 设置有问题，你可以试试我打包的 mpvnet

地址：[https://kutt.lckp.top/Rm4SZN](https://kutt.lckp.top/Rm4SZN)
密码：`7toz`

解压后直接使用就行，如果还不行再找我，如果可以证明是你的 mpv 设置的问题

**Comment by LuckyPuppy514** [comment]
记得改下软件路径：安装目录/mpvnet.exe
保存设置后下载注册表重新添加

**Comment by cancundeyingzi** [comment]
谢谢,经过逐个替换尝试,发现profiles.conf有问题.

**Comment by cancundeyingzi** [comment]
很神奇,今天又不行了,包括你的那个,调起后黑屏一会自动闪退,(确认注册表,clash路线没有问题),clash开启tun模式后正常
