### ISSUE TITLE
通过MPV右下角下载按钮下载的视频没声音

### ISSUE THREAD

**Issue by ldy779** [LuckyPuppy514/Play-With-MPV#108]
- 操作系统：windows10
- 浏览器：360极速浏览器
- 下载的视频格式为m4s
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/58897899/0e5a5b7f-6c1a-4b7a-b935-3c7820ecfdcc)

**Comment by LuckyPuppy514** [comment]
这个功能非本项目提供，建议自行寻找解决方案
