### ISSUE TITLE
能否设置手动选择清晰度

### ISSUE THREAD

**Issue by Neomanbeta** [LuckyPuppy514/Play-With-MPV#11]
现在是直接按照最高清晰度播放，如果我看YouTube，有的视频直接就4k了，能否给个设置，让用户可以手动选择清晰度，然后再点击图标启动MPV？

**Comment by LuckyPuppy514** [comment]
可以，等我有空在设置里面加个选项 😂

**Comment by LuckyPuppy514** [comment]
已添加，升级到最新版即可  

![image](https://user-images.githubusercontent.com/53246532/196562481-61ffb865-1699-48e6-8294-d05c7ab7085a.png)
