### ISSUE TITLE
https://jiohub.top/网站中有些视频无法出现调用按钮

### ISSUE THREAD

**Issue by fyfyluck** [LuckyPuppy514/Play-With-MPV#113]
https://jiohub.top/网站中有些视频无法出现调用按钮，有些可以。举例：https://jiohub.top/watch/264?speed=5可以出现调用按钮，https://jiohub.top/watch/27686无法出现调用按钮

**Comment by LuckyPuppy514** [comment]
正常，同一个网站不同视频也可能需要不同的解析方式，我看了下，暂时没法弄，建议到其他网站观看

**Comment by orz12** [comment]
#115 已添加
