### ISSUE TITLE
视频颜色不正常，出现在B站某些电影、视频

### ISSUE THREAD

**Issue by Galahahad** [LuckyPuppy514/Play-With-MPV#117]
- 操作系统：windows10
- 浏览器：chrome
- 复现问题的操作：https://www.bilibili.com/bangumi/play/ep454146
- 出现的具体问题：视频颜色不正常，在两台电脑上问题复现
- 配置截图：
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/61223137/41d61dda-9a3a-462e-8515-d48e89e2e02a)
- 报错截图：建议全屏，或浏览器全屏截图
- ![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/61223137/439c955f-d55d-4cae-8142-e232c1706682)

**Comment by LuckyPuppy514** [comment]
这个不是脚本问题，是你播放器设置问题，看你截图这个颜色发绿，应该是杜比视界的资源，mpv 选项设置，vo 选择 gpu-next

![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/fae41b2e-5408-48a0-a754-b882053fb1b6)
