### ISSUE TITLE
有些网站无法出现调用按钮

### ISSUE THREAD

**Issue by MrPinku** [LuckyPuppy514/Play-With-MPV#119]
- 操作系统：windows10
- 浏览器：chrome
- 复现问题的操作：以下两个网址都不出现按钮
- https://www.libvio.pro/play/714890512-1-2.html
- https://www.nivod4.tv/YeClpGXOt58F3QmAp9bx5CnaBrO4txhU-27-0-0-0-play.html?sc=6bb1aa9619ece1f6a00124a66a6fb8b6
- libvio看芙莉莲倒是没问题

**Comment by orz12** [comment]
泥视频我在 #120 添加了支持，libvio我遇到了很奇怪的情况，暂时还不知道原因

**Comment by orz12** [comment]
已尝试在 #120  解决libvio的问题，但方式比较激进

**Comment by LuckyPuppy514** [comment]
> 已尝试在 #120 解决libvio的问题，但方式比较激进

已发布，亲测没问题 👍

![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/d7bd84a8-c763-44b9-bedb-938d9af38fd0)
