### ISSUE TITLE
是否可以添加对b站直播间的支持

### ISSUE THREAD

**Issue by Leviathanlzx** [LuckyPuppy514/Play-With-MPV#12]
之前用火狐那个send to mpv player在b站直播有些打得开有些打不开，打不开的出现以下报错:
![图片](https://user-images.githubusercontent.com/102511297/197720437-f960daae-abba-44d0-a334-3e2a0881507d.png)
不知道这个插件可以实现吗，毕竟用这个看管人太爽了😍

**Comment by Leviathanlzx** [comment]
帅！

**Comment by Leviathanlzx** [comment]
我又试了一下，发现插件突然无法在火狐里工作了，具体体现为无法唤醒mpvnet，点击蓝色箭头没有反应，我尝试重装也是如此。但我之后在edge里重新安装，发现它运行得非常完美。不知道这个插件在火狐里的问题是不是只有我这里有

**Comment by LuckyPuppy514** [comment]
我这里火狐也是正常的 😂

**Comment by LuckyPuppy514** [comment]
![image](https://user-images.githubusercontent.com/53246532/197843651-566d54b2-b635-4ecb-8512-5aff22ec7b11.png)

**Comment by LuckyPuppy514** [comment]
为何要回退版本？你注册表重新添加试试

**Comment by Leviathanlzx** [comment]
已经解决了！我把火狐重新装了一遍就可以使用了，应该不是插件的问题，不知道火狐又抽了什么疯😅

**Comment by LuckyPuppy514** [comment]
🤣
