### ISSUE TITLE
不显示图标

### ISSUE THREAD

**Issue by Ziluomu** [LuckyPuppy514/Play-With-MPV#121]
与greasy fork里的https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv/discussions/204871此贴问题相同，调整图标位置后图标不再显示，降级到3.9.3也没显示，恢复到1.0.0后有显示

**Comment by LuckyPuppy514** [comment]
可能是你安装过有 BUG 的版本，然后当时又把图标拖出屏幕外了，按下列操作，改下坐标为 0，0 即可

![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/3c533382-a850-4c2f-a9f8-ed0143df706a)
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/4427bebb-6303-4294-8dae-4b485f86449e)
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/144af335-af17-4af6-a38a-2c6a37fbc91e)

**Comment by Ziluomu** [comment]
已解决，多谢大佬
