### ISSUE TITLE
左下角的按钮可选显示

### ISSUE THREAD

**Issue by hu3rror** [LuckyPuppy514/Play-With-MPV#122]
- 操作系统：Windows 11
- 浏览器：chrome

## 目前问题
目前会同时出现多个按钮，每次用都要顿一下思考按哪一个

## 预期解决效果1:
设置了 MPV 就显示 MPV 的按钮，同理设置 PotPlayer 就显示 PotPlayer。不设置不显示。

## 预期解决效果2:
只显示一个播放按钮，通过设置默认值，可跳转到 MPV 或 PotPlayer 设置为默认的那个

您意下如何呢？

**Comment by LuckyPuppy514** [comment]
可以，但是得等我有空，最近暂时没空 😂

**Comment by orz12** [comment]
已添加 #123 ，使用了预期解决效果1的方式

**Comment by LuckyPuppy514** [comment]
> 已添加 #123 ，使用了预期解决效果1的方式

已发布 👍
