### ISSUE TITLE
how to revert play-with-mpv registry?

### ISSUE THREAD

**Issue by marcust10** [LuckyPuppy514/Play-With-MPV#127]
- 操作系统：windows10
- 浏览器：brave 
- 复现问题的操作：要撤回mpv-install.reg
- 出现的具体问题：怎么不使用mpv-install.reg
- 配置截图：
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/14249658/22da47fe-3929-49bb-869e-c0d91be66384)

- 报错截图：建议全屏，或浏览器全屏截图

**Comment by orz12** [comment]
click 删除注册表, you can download mpv-delete.reg, after that, just double click mpv-delete.reg to import, it will revert the registy.
