### ISSUE TITLE
使用脚本时正常打开了powershell但没有打开mpv

### ISSUE THREAD

**Issue by VincenzoJane** [LuckyPuppy514/Play-With-MPV#129]
- 操作系统： windows10
- 浏览器：chrome 
- 复现问题的操作：输入路径保存设置下载安装注册表之后，刷新网页，问我要不要打开powershell，打开之后闪一下就退了，并没有打开mpv
- 出现的具体问题：powershell打开后闪退，打不开mpv
- 配置截图：
![1](https://github.com/LuckyPuppy514/Play-With-MPV/assets/121120637/de77b3fe-46d6-41d6-942c-8e37b4e8613b)
- 报错截图：
![2](https://github.com/LuckyPuppy514/Play-With-MPV/assets/121120637/e6202429-650b-4b4a-b8aa-8b81e0daaeaf)

**Comment by orz12** [comment]
这种可能是mpv视频下载失败了，你点击左上角小圆形状的i图标看一下里面的链接是否正常，在mpv里能不能打开这个视频流

**Comment by orz12** [comment]
另外这个是普遍的现象 还是只有特定几个网站或者是视频 才会出现的？

**Comment by VincenzoJane** [comment]
> 这种可能是mpv视频下载失败了，你点击左上角小圆形状的i图标看一下里面的链接是否正常，在mpv里能不能打开这个视频流

可以，我复制里面的视频链接到mpv里可以打开

**Comment by VincenzoJane** [comment]
> 另外这个是普遍的现象 还是只有特定几个网站或者是视频 才会出现的？

都打不开

**Comment by VincenzoJane** [comment]
> 这种可能是mpv视频下载失败了，你点击左上角小圆形状的i图标看一下里面的链接是否正常，在mpv里能不能打开这个视频流

不过换了个视频试，发现打不开了，mpv还闪退了

**Comment by LuckyPuppy514** [comment]
1. 你确定这个路径没错？看起来就很奇怪 😂，路径错误也会闪退
2. 不要安装在 C 盘，很容易权限不足打不开，就会闪退

![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/0931e79c-a358-4e73-8dc8-0f340ecf51af)

**Comment by VincenzoJane** [comment]
> 1. 你确定这个路径没错？看起来就很奇怪 😂，路径错误也会闪退
> 2. 不要安装在 C 盘，很容易权限不足打不开，就会闪退
> 
> ![image](https://private-user-images.githubusercontent.com/53246532/285640222-0931e79c-a358-4e73-8dc8-0f340ecf51af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5OTU1OTIsIm5iZiI6MTcwMDk5NTI5MiwicGF0aCI6Ii81MzI0NjUzMi8yODU2NDAyMjItMDkzMWU3OWMtYTM1OC00ZTczLThkYzgtMGYzNDBlY2Y1MWFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDEwNDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwYzZlYTgwZmRkMGYzMTgyMmQ4Y2JiMzM0NjE1ZmRiYjAzNWU0NjllYWM5MzYxNGI4OWQ5NTNkYmU5ZDVkNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1FneOrNAEw1SqEqojD5phRMGMr-UUoTtxh-Rezj9xvQ)

谢谢，我搞好了，路径有点问题
