### ISSUE TITLE
点击播放后403了，无法访问

### ISSUE THREAD

**Issue by ssxwcz** [LuckyPuppy514/Play-With-MPV#13]
![image](https://user-images.githubusercontent.com/43665491/197809806-612f7946-18b7-4c8b-8747-497336a88906.png)

**Comment by ssxwcz** [comment]
> 为何你用浏览器打开播放链接？点击播放按钮，链接应该是这样子的
> 
> ```
> mpv://%22https://xy49x86x255x20xy.mcdn.bilivideo.cn:4483/upgcxcode/11/69/871486911/871486911-1-100027.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1666717459&gen=playurlv2&os=mcdn&oi=1032673045&trid=00006bf49950101347d587a0d671ebac19bdu&mid=356927809&platform=pc&upsig=d9a0f4fb2ca4f5556db4811c36569eb2&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&mcdnid=2002405&bvc=vod&nettype=0&orderid=0,3&agrr=1&bw=57999&logo=A0000002%22%20--no-terminal%20--ss=%2200:04%22%20--audio-file=%22https://xy49x86x255x20xy.mcdn.bilivideo.cn:4483/upgcxcode/11/69/871486911/871486911_nb3-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1666717459&gen=playurlv2&os=mcdn&oi=1032673045&trid=00006bf49950101347d587a0d671ebac19bdu&mid=356927809&platform=pc&upsig=a30d86e7699d44584b164655a277c727&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&mcdnid=2002405&bvc=vod&nettype=0&orderid=0,3&agrr=1&bw=40520&logo=A0000002%22%20--http-header-fields=%22referer:%20https://www.bilibili.com,%20user-agent:%20Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/106.0.0.0%20Safari/537.36%20Edg/106.0.1370.52%22%20--script-opts=%22cid=871486911%22%20--force-media-title=%22%E4%B8%96%E7%95%8C%E6%9C%AB%E6%97%A5%E6%9F%B4%E7%8A%AC%E4%B8%BA%E4%BC%B4%E7%AC%AC33%E9%9B%86-%E7%95%AA%E5%89%A7-%E9%AB%98%E6%B8%85%E7%8B%AC%E5%AE%B6%E5%9C%A8%E7%BA%BF%E8%A7%82%E7%9C%8B-bilibili-%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%22
> ```

我并没有用浏览器打开，我点击按钮之后会跳出一个mpv，但是立马退出了，然后浏览器中打开了找个播放链接

**Comment by ssxwcz** [comment]
![image](https://user-images.githubusercontent.com/43665491/197810978-bebfafe9-8fb8-46ca-b7c8-b38ede978c44.png)
已经添加过注册表了

**Comment by LuckyPuppy514** [comment]
你有QQ么

**Comment by ssxwcz** [comment]
```batch
cmd /V:ON /C "FOR /F "tokens=* USEBACKQ" %%F IN (`powershell -command "Add-Type -AssemblyName System.Web;[System.Web.HTTPUtility]::UrlDecode('%1')"`) DO (SET param=%%F) & SET param=!param:mpv://=! & start /min "E:/Program Files/mpv-lazy/mpv.com" !param!"
```
这是我最终注册表生成的命令

**Comment by LuckyPuppy514** [comment]
1. 为何你的路径会有双引号，程序生成的不会带有双引号
2. 路径不要有空格，中文等特殊符号，否则只能自己手动修改注册表，我也不敢保证可以

**Comment by LuckyPuppy514** [comment]
不要添加双引号，不要空格
![image](https://user-images.githubusercontent.com/53246532/197812920-79c1e734-58b6-4da1-968e-f54dc84509f9.png)
![image](https://user-images.githubusercontent.com/53246532/197813014-f72a8b98-1965-4a3d-a84b-bfcde75ce375.png)

**Comment by LuckyPuppy514** [comment]
🤣 我说咋回事呢，直接双引号肯定不行的，不加双引号，有个空格可能可以，不过还是建议：
1. 不要有空格，中文等特殊字符
2. 最好也不要放在C盘

**Comment by ssxwcz** [comment]
加空格肯定不行的，我测试过，所以我才添加双引号试试的，我再看看吧

**Comment by LuckyPuppy514** [comment]
那只能换个路径了，我文档里面有提醒的，没办法 😂

**Comment by ssxwcz** [comment]
嗯，好的，换个路径就行了，Windows这个祖传的program files的空格还是有点坑啊，多谢
