### ISSUE TITLE
`--script-opts`建议改为`--script-opts-append`

### ISSUE THREAD

**Issue by verygoodlee** [LuckyPuppy514/Play-With-MPV#130]
https://github.com/LuckyPuppy514/Play-With-MPV/blob/cb6cd1d70434f59a7f29d1dcb9d39d0f60974123/play-with-mpv.user.js#L1998
如果在mpv.conf中设置了`--script-opts`，这个启动参数会把它覆盖掉，使用`--script-opts-append`在后面追加，而不是覆盖

**Comment by hooke007** [comment]
我没仔细看，这个cid出自哪个脚本

**Comment by verygoodlee** [comment]
出自这个加载弹幕的脚本，根据cid查询下载弹幕
https://github.com/itKelis/MPV-Play-BiliBili-Comments/blob/f8573bc357c1f0129922e613bc85c1df7b27570e/scripts/bilibiliAssert/main.lua#L17

**Comment by LuckyPuppy514** [comment]
我本地试了下 `--script-opts-append` 不行
需要写弹幕脚本的大佬看看是否可以传到其他参数里面取，他那边改了后我这边配合修改下就行 😢

**Comment by verygoodlee** [comment]
我测试可行的，很简单的一个测试用例，你试试
```
# mpv.conf 修改stats字体为黑色
script-opts-append=stats-font_color=000000
```
- `--script-opts="cid=${cid}"`  弹幕加载成功，stats字体为白色
![屏幕截图 2023-12-14 204737](https://github.com/LuckyPuppy514/Play-With-MPV/assets/45035465/0fe9b670-522b-4c3b-b688-bae68d88918f)
- `--script-opts-append="cid=${cid}"`  弹幕加载成功，stats字体为黑色
![屏幕截图 2023-12-14 204845](https://github.com/LuckyPuppy514/Play-With-MPV/assets/45035465/d23cde2b-a8fa-4a57-beaf-d41ff8840f0d)

**Comment by LuckyPuppy514** [comment]
我又试了下，我发现 mpv / mpv-lazy 是可以的，是 mpvnet 不支持 😢

**Comment by verygoodlee** [comment]
mpv.net是基于libmpv的二次开发，可能没对[List Options](https://mpv.io/manual/master/#list-options)做特殊处理
> If you want to pass a value without interpreting it for escapes or ,, it is recommended to use the -append variant. When using libmpv, prefer using MPV_FORMAT_NODE_MAP; when using a scripting backend or the JSON IPC, use an appropriate structured data type.

**Comment by LuckyPuppy514** [comment]
[v4.0.2](https://github.com/LuckyPuppy514/Play-With-MPV/commit/c16c97e0f2e9b6a4f007f8cc6a2d77208afcbc63) 暂时把非 mpvnet 的播放器改成了 `--script-opts-append`，mpvnet 还是保持 `--script-opts`
