### ISSUE TITLE
mpv无法播放视频

### ISSUE THREAD

**Issue by yesflay** [LuckyPuppy514/Play-With-MPV#131]
- 操作系统：windows10
- 浏览器：firefox
![mpv](https://github.com/LuckyPuppy514/Play-With-MPV/assets/153925889/96bcde9c-27e2-4567-b29d-c5e8b1a9d91c)

**Comment by LuckyPuppy514** [comment]
请按 [问题模板](https://github.com/LuckyPuppy514/Play-With-MPV/issues/new?assignees=&labels=&projects=&template=%E9%97%AE%E9%A2%98%E5%8F%8D%E9%A6%88.md&title=) 提问
