### ISSUE TITLE
脚本弹出mpv后无法播放视频

### ISSUE THREAD

**Issue by yesflay** [LuckyPuppy514/Play-With-MPV#132]
- 操作系统：windows10
- 浏览器：Firefox 122
- 复现问题的操作：正常打开视频网页，脚本自动弹出mpv窗口
- 出现的具体问题：弹出mpv后无法播放视频
- 配置截图：i3 10100f+GTX1660ti，16GB 2666Mhz内存，Firefox 122使用最新版tampermonkey管理器
![101611](https://github.com/LuckyPuppy514/Play-With-MPV/assets/153925889/60d04215-9439-46db-b5e6-650bd93fab07)
- 报错截图：
![290846590-96bcde9c-27e2-4567-b29d-c5e8b1a9d91c](https://github.com/LuckyPuppy514/Play-With-MPV/assets/153925889/f8e39e02-6967-4274-87ac-c1ac4ee7f552)

**Comment by yesflay** [comment]
![101910](https://github.com/LuckyPuppy514/Play-With-MPV/assets/153925889/fa47903c-1afc-425c-98bc-3c7be0e1c20d)
未更改自定义设置，应该是默认状态

**Comment by LuckyPuppy514** [comment]
F12，打开控制台，清空日志后，重新点击播放按钮，截图看看

**Comment by yesflay** [comment]
> F12，打开控制台，清空日志后，重新点击播放按钮，截图看看

打开浏览器的调试界面还是mpv的调试界面？

**Comment by LuckyPuppy514** [comment]
浏览器

**Comment by yesflay** [comment]
> 浏览器

我清空了日志，但是反复尝试3次后问题依然存在，可以给出更详细的说明或者其他解决方案吗？

**Comment by LuckyPuppy514** [comment]
麻烦认真看回复，我让你截图，不是说这样可以解决

**Comment by yesflay** [comment]
> 麻烦认真看回复，我让你截图，不是说这样可以解决

抱歉是我自己没有认真阅读回复，日志输出如下
![图片](https://github.com/LuckyPuppy514/Play-With-MPV/assets/153925889/65c84b25-cf9d-4cb1-96c2-4f4852865b7e)

**Comment by yesflay** [comment]
> 麻烦认真看回复，我让你截图，不是说这样可以解决

我在禁用了about:config中samesite相关选项之后，问题依然存在

**Comment by orz12** [comment]
有加群吗？

**Comment by LuckyPuppy514** [comment]
1. F12 打开调试窗口后，点击控制台，并清空所有日志
2. 重新点击左下角的 Play-With-MPV 的播放按钮
3. 像我这样子截图
4. 把日志打印的很长的链接右键复制发上来

![20231216171055](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/e95d3dfd-5b55-40f2-8987-c7c3a1686831)

```txt
mpv://%22https://xy122x192x233x42xy.mcdn.bilivideo.cn:8082/v1/resource/1325890920-1-100050.m4s?agrr=1&build=0&buvid=8FB34259-56B3-21FE-C559-11E8D2578EF609710infoc&bvc=vod&bw=131464&deadline=1702725003&e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M%3D&f=u_0_0&gen=playurlv2&logo=A0000001&mcdnid=1003361&mid=356927809&nbs=1&nettype=0&oi=2028458463&orderid=0%2C3&os=mcdn&platform=pc&sign=39723d&traceid=trIcispsGULIIo_0_e_N&uipk=5&uparams=e%2Cuipk%2Cnbs%2Cdeadline%2Cgen%2Cos%2Coi%2Ctrid%2Cmid%2Cplatform&upsig=ba15308543dc2548d26287691fb006e5%22%20--audio-file=%22https://xy27x184x116x81xy.mcdn.bilivideo.cn:8082/v1/resource/1325890920-1-30280.m4s?agrr=1&build=0&buvid=8FB34259-56B3-21FE-C559-11E8D2578EF609710infoc&bvc=vod&bw=10287&deadline=1702725003&e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M%3D&f=u_0_0&gen=playurlv2&logo=A0000001&mcdnid=1003361&mid=356927809&nbs=1&nettype=0&oi=2028458463&orderid=0%2C3&os=mcdn&platform=pc&sign=85c968&traceid=trOJKhOhxQImlH_0_e_N&uipk=5&uparams=e%2Cuipk%2Cnbs%2Cdeadline%2Cgen%2Cos%2Coi%2Ctrid%2Cmid%2Cplatform&upsig=93af9b83ee89263ac5dfd619eeec1af7%22%20--http-header-fields=%22referer:%20https://www.bilibili.com%22%20--script-opts=%22cid=1325890920%22%20--force-media-title=%22%E5%8D%8E%E7%A1%95ProArt%20602%E6%B5%8B%E8%AF%84%EF%BC%9A%E5%82%B2%E8%A7%86%E7%BE%A4%E9%9B%84%EF%BC%81_%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9_bilibili%22
```

**Comment by orz12** [comment]
可能要在这里的【信息】处点击才能看到。
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/17450420/2bd7c0a9-b2be-460e-9831-1fc85c1c1123)

**Comment by yesflay** [comment]
> 有加群吗？

没有，可以告诉群号吗？谢谢

**Comment by yesflay** [comment]
> 1. F12 打开调试窗口后，点击控制台，并清空所有日志
> 
>     2. 重新点击左下角的 Play-With-MPV 的播放按钮
> 
>     3. 像我这样子截图
> 
>     4. 把日志打印的很长的链接右键复制发上来
> 
> 
> ![20231216171055](https://private-user-images.githubusercontent.com/53246532/290983218-e95d3dfd-5b55-40f2-8987-c7c3a1686831.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MjIxMjAsIm5iZiI6MTcwMjcyMTgyMCwicGF0aCI6Ii81MzI0NjUzMi8yOTA5ODMyMTgtZTk1ZDNkZmQtNWI1NS00MGYyLTg5ODctYzdjM2ExNjg2ODMxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDEwMTcwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMjAwMWExMDQwOWI0YTIzMmMzNDBlNTU0ODE1NWU4MzNkYzYzN2M1NmYzMjQ0ZGZjMWIxOWFiMGY0YWVjNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4hmWobzJp26I_usJapzp2FEYPUPJSgicUSaOQiSc1N4)
> 
> ```
> mpv://%22https://xy122x192x233x42xy.mcdn.bilivideo.cn:8082/v1/resource/1325890920-1-100050.m4s?agrr=1&build=0&buvid=8FB34259-56B3-21FE-C559-11E8D2578EF609710infoc&bvc=vod&bw=131464&deadline=1702725003&e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M%3D&f=u_0_0&gen=playurlv2&logo=A0000001&mcdnid=1003361&mid=356927809&nbs=1&nettype=0&oi=2028458463&orderid=0%2C3&os=mcdn&platform=pc&sign=39723d&traceid=trIcispsGULIIo_0_e_N&uipk=5&uparams=e%2Cuipk%2Cnbs%2Cdeadline%2Cgen%2Cos%2Coi%2Ctrid%2Cmid%2Cplatform&upsig=ba15308543dc2548d26287691fb006e5%22%20--audio-file=%22https://xy27x184x116x81xy.mcdn.bilivideo.cn:8082/v1/resource/1325890920-1-30280.m4s?agrr=1&build=0&buvid=8FB34259-56B3-21FE-C559-11E8D2578EF609710infoc&bvc=vod&bw=10287&deadline=1702725003&e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M%3D&f=u_0_0&gen=playurlv2&logo=A0000001&mcdnid=1003361&mid=356927809&nbs=1&nettype=0&oi=2028458463&orderid=0%2C3&os=mcdn&platform=pc&sign=85c968&traceid=trOJKhOhxQImlH_0_e_N&uipk=5&uparams=e%2Cuipk%2Cnbs%2Cdeadline%2Cgen%2Cos%2Coi%2Ctrid%2Cmid%2Cplatform&upsig=93af9b83ee89263ac5dfd619eeec1af7%22%20--http-header-fields=%22referer:%20https://www.bilibili.com%22%20--script-opts=%22cid=1325890920%22%20--force-media-title=%22%E5%8D%8E%E7%A1%95ProArt%20602%E6%B5%8B%E8%AF%84%EF%BC%9A%E5%82%B2%E8%A7%86%E7%BE%A4%E9%9B%84%EF%BC%81_%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9_bilibili%22
> ```

Firefox的操作和这个不太一样

**Comment by yesflay** [comment]
![20231216182](https://github.com/LuckyPuppy514/Play-With-MPV/assets/153925889/be508a2c-d9a8-4509-b5b1-7e65cc0fc1cf)
我只好把整个记录都截图下来了

**Comment by LuckyPuppy514** [comment]
我只能说我这边没问题，我下载了个最新版的火狐，按你的说法可以打开 mpv，那更有可能是你的浏览器设置或者 mpv 设置的问题，还有你可以到导航页试试其他网站是否可行，你浏览器设置和mpv设置的问题只能自行解决，我办法给你一个一个说

![20231216190654](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/69f22eea-e8f5-455d-baff-a561f4187744)

**Comment by LuckyPuppy514** [comment]
浏览器安装后除了下载油猴插件和我这个脚本没做任何其他设置改动，点击播放时会提示一些提示全都要允许
mpv 一般 github 上的原生版 mpv，mpv-lazy，mpvnet，以及我博客自用的 mpvnet 应该都是开箱就可以使用
你有问题可以下载任意一个版本，不要修改任何设置进行尝试

**Comment by LuckyPuppy514** [comment]
还有问题建议加Q群：921905633，找我远程，让你操作你操作不明白我也没办法看出来是什么问题

**Comment by yesflay** [comment]
> 还有问题建议加Q群：921905633，找我远程，让你操作你操作不明白我也没办法看出来是什么问题

请问你打算用哪个软件远程？

**Comment by yesflay** [comment]
好了，问题解决，谢谢作者的热心帮助。问题就出在Firefox Nightly向mpv传递的函数上，可能是mozilla那边测试新功能的缘故。我去ftp.mozilla.org里找到了普通版Firefox的国际版，成功把我的数据迁移了过去，这样就可以正常使用了。
