### ISSUE TITLE
jquery加载失败，左下角图标出不来

### ISSUE THREAD

**Issue by verygoodlee** [LuckyPuppy514/Play-With-MPV#133]
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/45035465/c54f6f59-878e-4904-b251-98e29916fd65)

不认识`$`这个符号，应该是jquery的问题，试了一下这两个js链接都打不开了，电信和联通网都试了，不会是被墙了吧，要换其他cdn了
https://github.com/LuckyPuppy514/Play-With-MPV/blob/93b9c2c850a4fb5249179faad247767065555656/play-with-mpv.user.js#L127-L128

**Comment by verygoodlee** [comment]
手动换了这个cdn之后可以了  https://www.bootcdn.cn
```javascript
// @require                 https://cdn.bootcdn.net/ajax/libs/jquery/3.2.1/jquery.min.js
// @require                 https://cdn.bootcdn.net/ajax/libs/blueimp-md5/2.3.0/js/md5.min.js
```

**Comment by LuckyPuppy514** [comment]
没有被墙，一般是你的 DNS 用的运营商默认的，导致域名解析失败导致的，打开 cmd 执行以下命令检查 DNS

```bat
nslookup unpkg.com
```

连通性测试

```bat
telnet 104.16.126.175 443
```

DNS建议使用阿里云 `223.5.5.5` 和谷歌 `8.8.8.8`

**Comment by verygoodlee** [comment]
确实用的运行商的dns，解析出来是104.16.125.175，ping不通，你给的104.16.126.175也ping不通

**Comment by LuckyPuppy514** [comment]
不要用 ping， 禁 ping 了，用 telnet 测

**Comment by verygoodlee** [comment]
telnet老早测过了，不通

**Comment by LuckyPuppy514** [comment]
那就是你自己的网络问题了，我移动和手机数据都没问题

**Comment by verygoodlee** [comment]
墙是分地区的，可能有些地方被墙了，有些地方正常

**Comment by LuckyPuppy514** [comment]
暂时还没收到其他人反馈，unpkg 这个用了挺久了，还是比较稳的，要是反馈的人多了，我再换一个好了
你先自己本地换着用吧 😂

**Comment by verygoodlee** [comment]
广东地区，手机移动网，家里的联通宽带、公司的电信宽带，全部阵亡

**Comment by orz12** [comment]
> 暂时还没收到其他人反馈，unpkg 这个用了挺久了，还是比较稳的，要是反馈的人多了，我再换一个好了 你先自己本地换着用吧 😂

我前几天也在你的群里看到一个$识别不出来的 但是当时我以为是安全策略的问题 没想到是jquery源

**Comment by verygoodlee** [comment]
阿里云服务器华南深圳区也阵亡了，基本确定这边是有墙的
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/45035465/ea9d19e2-8a4f-4ba7-b65e-401ec7079201)

**Comment by LuckyPuppy514** [comment]
[v4.0.4 换了个CDN，你们再试试](https://github.com/LuckyPuppy514/Play-With-MPV/commit/0869d38ca8d378b13c61ec5ea26a6379f0f38d0d)

[测速结果](https://tool.chinaz.com/speedtest/lf26-cdn-tos.bytecdntp.com)

![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/3ff1a2aa-c273-489a-9020-5fe283d6980d)

**Comment by verygoodlee** [comment]
https://github.com/LuckyPuppy514/Play-With-MPV/blob/0869d38ca8d378b13c61ec5ea26a6379f0f38d0d/play-with-mpv.user.js#L128
这个好像跟之前的不是同一款，没有`MD5()`这个函数，欧乐影院应该有问题
https://github.com/LuckyPuppy514/Play-With-MPV/blob/0869d38ca8d378b13c61ec5ea26a6379f0f38d0d/play-with-mpv.user.js#L3120

**Comment by LuckyPuppy514** [comment]
MD5 是没问题，但是欧乐影院网站更新了，变动还比较大，我暂时没去适配 😂
