### ISSUE TITLE
mpv播放器懒人版youtube不行

### ISSUE THREAD

**Issue by zxc173123** [LuckyPuppy514/Play-With-MPV#134]
- 操作系统：windows10
- 浏览器：360极速浏览器X，Chromium119内核
- 复现问题的操作：正常操作
- 出现的具体问题：过一会mpv弹出但是没有视频内容只是打开了，播放b站就没问题
- 配置截图：![QQ截图20231228173220](https://github.com/LuckyPuppy514/Play-With-MPV/assets/56154254/12250459-4afd-44b3-9c9c-c986d69bde0f)
- 报错截图：没报错

**Comment by LuckyPuppy514** [comment]
确保你的 mpv 安装了 yt-dlp，并且升级到最新版，一般就在安装目录：`yt-dlp.exe`

[https://github.com/yt-dlp/yt-dlp/releases](https://github.com/yt-dlp/yt-dlp/releases)
