### ISSUE TITLE
How do I play using VLC?

### ISSUE THREAD

**Issue by cleuton4k** [LuckyPuppy514/Play-With-MPV#136]
![667](https://github.com/LuckyPuppy514/Play-With-MPV/assets/90144967/fd9e80d8-44ce-4606-a7cd-09278b89eff0)
![668](https://github.com/LuckyPuppy514/Play-With-MPV/assets/90144967/8fa015fd-67ba-4258-b2fa-7988ceef00e9)
- 操作系统：windows7 / windows10/11 / ...
- 浏览器：chrome / edge / ...
- 复现问题的操作：点击哪里
- 出现的具体问题：出现了什么情况
- 配置截图：建议全屏，或浏览器全屏截图
- 报错截图：建议全屏，或浏览器全屏截图

**Comment by LuckyPuppy514** [comment]
try this `vlc://${videoUrl}` or `vlc://${EvideoUrl}`

![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/188a0323-840d-4aff-a143-edff806258c1)

if not work, you may need add reg like this: [https://gist.github.com/aykxt/1aff15ba794061b8b4dc47e5aa1175e6](https://gist.github.com/aykxt/1aff15ba794061b8b4dc47e5aa1175e6)

**Comment by cleuton4k** [comment]
did not work

**Comment by LuckyPuppy514** [comment]
![20240119220244](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/70ca8ef1-a83e-42ed-841d-d570c74229ef)

```text
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome]
"ExternalProtocolDialogShowAlwaysOpenCheckbox"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge]
"ExternalProtocolDialogShowAlwaysOpenCheckbox"=dword:00000001

[HKEY_CLASSES_ROOT\vlc]
@="vlc Protocol"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\vlc\DefaultIcon]
@=""

[HKEY_CLASSES_ROOT\vlc\shell]
@=""

[HKEY_CLASSES_ROOT\vlc\shell\open]
@=""

[HKEY_CLASSES_ROOT\vlc\shell\open\command]
@="C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -WindowStyle Hidden -Command \"& {Add-Type -AssemblyName System.Web;$PARAMS=([System.Web.HTTPUtility]::UrlDecode('%1') -replace '^vlc://'); Start-Process -FilePath \\\"D://VLC//vlc.exe\\\" -ArgumentList $PARAMS}\""
```

1. replace `D://VLC//vlc.exe` with your vlc location and save as `vlc-install.reg`

2. double click `vlc-install.reg`

3. input `vlc://${videoUrl}` to `视频参数` and save

![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/c1cca406-eca9-4429-a891-e8ac61546391)

supported website: [https://www.lckp.top/play-with-mpv/index.html](https://www.lckp.top/play-with-mpv/index.html)

> some player may not work at some website without yt-dlp or special param config

other param setting you can find [here](https://wiki.videolan.org/VLC_command-line_help/)
