### ISSUE TITLE
mpv播放器不弹出

### ISSUE THREAD

**Issue by Ziluomu** [LuckyPuppy514/Play-With-MPV#139]
- 操作系统：windows 11 
- 浏览器：Firefox 122.0(64位)
- 复现问题的操作：按流程操作，视频出现暂停后，mpv播放器不弹出，换edge问题同样存在（油猴其他脚本均已关闭，扩展仅开油猴）
- 配置图
![图片](https://github.com/LuckyPuppy514/Play-With-MPV/assets/120566119/d555b284-d0ef-4aca-9480-80fe198d2801)

**Comment by LuckyPuppy514** [comment]
确保你保存设置后，下载注册表，并双击添加注册表信息了
如果确定添加了注册表信息，点击播放按钮，没有任何反应，一般是被杀毒软件拦截了，你可以关闭杀毒软件试试，可以的话自行百度/谷歌把拦截的 powershell.exe 添加到信任区

**Comment by Ziluomu** [comment]
补充：之前是可以正常使用的，前段时间暂停使用这个设备了，现在就用不了了。
           点击图标后网页正在播放的视频会暂停，并会出现一个瞬时powershell弹窗。
操作：注册表信息删除后重新保存设置并下载添加；设备未安装或运行杀软，将程序添加到windows的信任区后，问题仍未解决。
![图片](https://github.com/LuckyPuppy514/Play-With-MPV/assets/120566119/b45f6be2-6e5d-4818-8bc7-d21d3218d068)
![图片](https://github.com/LuckyPuppy514/Play-With-MPV/assets/120566119/8788e809-fafd-449e-aec1-806163bfbb59)

**Comment by LuckyPuppy514** [comment]
闪退一般是你软件路径有问题，或者网站链接失效了，换个站点试试
