### ISSUE TITLE
能不能增加一个网站的支持

### ISSUE THREAD

**Issue by SuperBlackWednesday** [LuckyPuppy514/Play-With-MPV#14]
https://www.btnull.org/这个网站经常挂掉  有个片库网站怀疑是一个人开的  结构都一样的
https://www.pkmp4.com/  加上这个网站可以吗？

**Comment by LuckyPuppy514** [comment]
已添加，更新到最新版即可：[点我更新](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv)  

![1668777151833_tuya](https://user-images.githubusercontent.com/53246532/202713198-54e45060-ed2f-4bed-8f67-0dc6902704eb.jpg)

**Comment by SuperBlackWednesday** [comment]
哦  十分感谢啊  大神有求必应啊

**Comment by SuperBlackWednesday** [comment]
那个还有个网站 看样子原理不一样的  但是片源很全  我用了好几年了 要不你看看？ 
https://www.o8tv.com/

**Comment by LuckyPuppy514** [comment]
> 

这个网站暂时没法解析 🥹
