### ISSUE TITLE
脚本很好用，但希望对更多的高清动画小站增加支持

### ISSUE THREAD

**Issue by s1mple11** [LuckyPuppy514/Play-With-MPV#16]
脚本本身沒有任何问题，但是支持的动画网站的片源质量不佳，希望可以对以下网站可以添加支持：
次元城动漫 https://www.cycdm01.top （全1080p）
橘子动漫 https://www.mgnacg.com （全1080p）
稀饭动漫 https://dick.xfani.com （全1080p）
异世界动漫 http://sbdm.net （720p与1080p混用）
異世界動漫 https://www.gqdm.net （720p与1080p混用）

或者可以写一个wiki教有java基础的用户自行改动脚本添加自己想要的支持网站？

**Comment by LuckyPuppy514** [comment]
1. 我看了下，你发的只有 `https://dick.xfani.com` 支持，我找时间加一下
2. 当前也有几个不错的动漫网站，比如：
https://libvio.fun
https://www.996dm.com
https://www.btnull.org
3. 至于怎么加网站，不同网站处理方式不一样，可以参考已经有的，最简单的就是类似这个
- 添加脚本生效网站：`// @include 网址` 
- 添加对应网站处理器：`class xxxHandler extends Handler`
```javascript
...
// @include                 https://www.btnull.org/py/*
...

// 无名小站
const BTNULL = "www.btnull.org";

class BtnullHandler extends Handler {
    getCurrentVideoUrl() {
        let html = document.documentElement.outerHTML;
        let index = html.indexOf("_BT.PC.player({url:'http") + 20;
        html = html.substring(index);
        index = html.indexOf("m3u8") + 4;
        currentVideoUrl = html.substring(0, index);
        handler.checkCurrentVideoUrl();
    }
}
```

**Comment by LuckyPuppy514** [comment]
稀饭动漫已经加上了，升级到最新版即可：[v2.3.2](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv)  

![image](https://user-images.githubusercontent.com/53246532/205561819-6096ed89-a1aa-468a-9735-1a133e8cbf1c.png)

**Comment by LuckyPuppy514** [comment]
橘子动漫也加上了，升级到最新版即可：[v2.3.3](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv)  

![image](https://user-images.githubusercontent.com/53246532/205564913-c8124304-7aab-4532-9303-6f7107bd0890.png)

**Comment by s1mple11** [comment]
这个响应速度，大佬太强了😂

**Comment by s1mple11** [comment]
> 橘子动漫也加上了，升级到最新版即可：[v2.3.3](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv)
> 
> ![image](https://user-images.githubusercontent.com/53246532/205564913-c8124304-7aab-4532-9303-6f7107bd0890.png)

突然想压榨一下大佬的生产力（？）
能再看看讯猫动漫(https://spdcat.net/)可以解析吗？

**Comment by LuckyPuppy514** [comment]
> > 橘子动漫也加上了，升级到最新版即可：[v2.3.3](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv)
> > ![image](https://user-images.githubusercontent.com/53246532/205564913-c8124304-7aab-4532-9303-6f7107bd0890.png)
> 
> 突然想压榨一下大佬的生产力（？） 能再看看讯猫动漫(https://spdcat.net/) 可以解析吗？

这个也不行 😂

**Comment by s1mple11** [comment]
> > > 橘子动漫也加上了，升级到最新版即可：[v2.3.3](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv)
> > > ![image](https://user-images.githubusercontent.com/53246532/205564913-c8124304-7aab-4532-9303-6f7107bd0890.png)
> > 
> > 
> > 突然想压榨一下大佬的生产力（？） 能再看看讯猫动漫(https://spdcat.net/) 可以解析吗？
> 
> 这个也不行 😂

不行就算了，现在已经很够了，大佬辛苦😂

**Comment by LuckyPuppy514** [comment]
> > > > 橘子动漫也加上了，升级到最新版即可：[v2.3.3](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv)
> > > > ![image](https://user-images.githubusercontent.com/53246532/205564913-c8124304-7aab-4532-9303-6f7107bd0890.png)
> > > 
> > > 
> > > 突然想压榨一下大佬的生产力（？） 能再看看讯猫动漫(https://spdcat.net/) 可以解析吗？
> > 
> > 
> > 这个也不行 😂
> 
> 不行就算了，现在已经很够了，大佬辛苦😂

我又稍微看了下，可以了，😁

![image](https://user-images.githubusercontent.com/53246532/205809002-825f85c7-4860-46a1-bf00-a9b97bdb5b52.png)
