### ISSUE TITLE
网站支持请求

### ISSUE THREAD

**Issue by jacylouis** [LuckyPuppy514/Play-With-MPV#17]
你好,可以把https://www.novipnoad.com也加入支持列表里吗

**Comment by LuckyPuppy514** [comment]
我看了下，伪装成 png 了，mpv 无法直接播放，暂时无法支持 🥹
![image](https://user-images.githubusercontent.com/53246532/207943519-288a7e3a-f3ff-4422-b2db-364eb88d382d.png)

**Comment by jacylouis** [comment]
感谢你的及时处理和回复
