### ISSUE TITLE
稀饭动漫(https://dick.xfani.com/)和橘子动漫(https://www.mgnacg.com/)的解析貌似失效了

### ISSUE THREAD

**Issue by s1mple11** [LuckyPuppy514/Play-With-MPV#18]
估计是网站更换了播放器逻辑

**Comment by LuckyPuppy514** [comment]
旧版是不行，现在在做代码优化和一些新功能，等过几天或一两周大版本更新就可以了

**Comment by LuckyPuppy514** [comment]
[👆 点我升级最新版即可 👆](https://kutt.lckp.top/lPFDM7)  

![image](https://user-images.githubusercontent.com/53246532/210130176-7499cc98-df08-43be-9103-67179a64290c.png)
