### ISSUE TITLE
自定义匹配规则未生效

### ISSUE THREAD

**Issue by 522654518** [LuckyPuppy514/Play-With-MPV#2]
java.io.FileNotFoundException: \app\config\application-format-custom.yml (绯荤粺鎵句笉鍒版寚瀹氱殑璺緞銆?

windows环境

**Comment by 522654518** [comment]
这个路径不对

**Comment by LuckyPuppy514** [comment]
你这个是我另外一个项目的吧QAQ
我正在搞个大版本更新，加了WEB UI，你要是不急，多等几天，还有些细节要改改
![image](https://user-images.githubusercontent.com/53246532/180644348-aff09e4a-1099-4621-8fd6-9c15ecac694b.png)

**Comment by 522654518** [comment]
> 你这个是我另外一个项目的吧QAQ 我正在搞个大版本更新，加了WEB UI，你要是不急，多等几天，还有些细节要改改 ![image](https://user-images.githubusercontent.com/53246532/180644348-aff09e4a-1099-4621-8fd6-9c15ecac694b.png)

厉害了 大佬 
我今天测试了一下 
如果jackett搜出来的种子里边有年份比如 2022 2017这种 
sonarr也识别不出来 显示unknow series 
建议用正则表达式把年份直接过滤掉

**Comment by LuckyPuppy514** [comment]
新版本发布了，新增 WebUI，可以自定义规则，也可以分享，下载规则，还有问题欢迎反馈
