### ISSUE TITLE
可以支持一下这两个网站吗？

### ISSUE THREAD

**Issue by 2584191127** [LuckyPuppy514/Play-With-MPV#20]
https://www.dqsj.cc/
https://www.omofun.top/

**Comment by LuckyPuppy514** [comment]
阳了，过段时间我看看 🥹

**Comment by LuckyPuppy514** [comment]
[👆 点我升级最新版即可 👆](https://kutt.lckp.top/lPFDM7)  

- 不支持：https://www.dqsj.cc
- 已添加：https://www.omofun.top （个别线路不行，请尝试切换线路）

![image](https://user-images.githubusercontent.com/53246532/210130256-c0304a17-1359-46dc-8102-f7e924e33933.png)
