### ISSUE TITLE
请问是否有办法隐藏掉mpv.com的cmd窗口？

### ISSUE THREAD

**Issue by DiritoTech** [LuckyPuppy514/Play-With-MPV#21]
![Quicker_20221223_010305](https://user-images.githubusercontent.com/96611541/209187956-b4c96cd6-bde7-4c42-ba04-ae992d9bbac9.png)
mpv播放一个视频时，总会同步启用mpv.com窗口驻留在任务栏上，很不美观，请问是否有相应办法隐藏？

**Comment by LuckyPuppy514** [comment]
暂时没有很好的办法可以隐藏，而且这个窗口会随 mpv 窗口关闭自动关闭，并不影响使用 😂
或者你可以考虑把任务栏设置成自动隐藏

**Comment by LuckyPuppy514** [comment]
> ![Quicker_20221223_010305](https://user-images.githubusercontent.com/96611541/209187956-b4c96cd6-bde7-4c42-ba04-ae992d9bbac9.png) mpv播放一个视频时，总会同步启用mpv.com窗口驻留在任务栏上，很不美观，请问是否有相应办法隐藏？

点击左下角的设置按钮，重新下载注册表，用记事本打开
最后一行中的 `mpv.com` 修改为 `mpv.exe` （或 mpvnet.com 修改为 mpvnet.exe）  
保存后双击，重新添加注册表，应该就可以了

![image](https://user-images.githubusercontent.com/53246532/209464365-074a5191-8b97-4ecd-b26c-2c9d09785855.png)

**Comment by LuckyPuppy514** [comment]
![image](https://user-images.githubusercontent.com/53246532/209464474-8a03dc30-c84f-4ccd-b97e-fdc7df861cf6.png)

**Comment by DiritoTech** [comment]
成功了,多谢大佬_(:з)∠)_
