### ISSUE TITLE
当MPV的路径里有空格的时候，没法启动MPV

### ISSUE THREAD

**Issue by RimoChan** [LuckyPuppy514/Play-With-MPV#22]
![image](https://user-images.githubusercontent.com/20064807/209474885-836b9e7e-4831-4616-b3d0-92bb9df15f65.png)

**Comment by LuckyPuppy514** [comment]
![image](https://user-images.githubusercontent.com/53246532/209485871-0dfee639-7863-43e0-8ee1-92a56cae287d.png)

**Comment by RimoChan** [comment]
不，我知道这个事实是已知的，但这并不意味着这不是bug吧？

**Comment by LuckyPuppy514** [comment]
是BUG，是我暂时无法解决的BUG 😂，主要是由于特殊字符在 注册表 和 cmd 经常报错
我尝试过一些办法但是都没效果，最简单的一劳永逸的办法就是不要使用带有特殊字符的路径
如果你有办法也欢迎提交 PR 😘
