### ISSUE TITLE
低端影视换域名了

### ISSUE THREAD

**Issue by jacylouis** [LuckyPuppy514/Play-With-MPV#23]
低端影视域名 换了 https://ddys.art 可能需要重新适配一下

**Comment by jacylouis** [comment]
本站备用域名：[ddys.art](https://ddys.art/) ，[ddys.pro](https://ddys.pro/)，网址发布页：[ddys.site](https://ddys.site/)。

**Comment by LuckyPuppy514** [comment]
收到，过两天大版本一起更新

**Comment by LuckyPuppy514** [comment]
[👆 点我升级最新版即可 👆](https://kutt.lckp.top/lPFDM7)  

![image](https://user-images.githubusercontent.com/53246532/210130334-5feda347-6ba9-41d3-8aca-b826b1dc9f4c.png)
