### ISSUE TITLE
是否支持mac，能否只获取视频直链？

### ISSUE THREAD

**Issue by fox493** [LuckyPuppy514/Play-With-MPV#24]

**Comment by LuckyPuppy514** [comment]
1. 不支持 mac，文档不是写着么，只支持 windows
2. 可以只获取视频直链，获取不了都没法播放

PS：你问的这两个问题，你只要稍微看看文档，思考下就知道答案了。。。
如果你是想支持 mac 的话，直说就得了，我可以告诉你
1. 我手头没有 mac 设备
2. mac 的浏览器调用外部程序方式不一样，而且没有注册表
所以只能等有熟悉 mac 的大佬 PR

至于直链，你获取了意义也不大，很多都是不能直接下载，或者直接播放的

**Comment by fox493** [comment]
可能我描述的有问题

> 1. 不支持 mac，文档不是写着么，只支持 windows
> 2. 可以只获取视频直链，获取不了都没法播放
> 
> PS：你问的这两个问题，你只要稍微看看文档，思考下就知道答案了。。。 如果你是想支持 mac 的话，直说就得了，我可以告诉你
> 
> 1. 我手头没有 mac 设备
> 2. mac 的浏览器调用外部程序方式不一样，而且没有注册表
>    所以只能等有熟悉 mac 的大佬 PR
> 
> 至于直链，你获取了意义也不大，很多都是不能直接下载，或者直接播放的

可能我描述的有问题吧，我获取到视频链接在mac设备上通过mpv打开也是可以观看的呀，但是脚本只支持一键打开，链接是不可见的。不过倒是可以在控制台报错信息里找到这个链接，大部分资源也可以正常观看

**Comment by LuckyPuppy514** [comment]
新版本支持自定义播放器了，mac 设备理论上也可以一键播放    
比如可以使用 iina 一键播放，具体设置可以 [查看文档](https://github.com/LuckyPuppy514/Play-With-MPV#43-%E8%87%AA%E5%AE%9A%E4%B9%89)
如果你想提取视频链接，也可以把参数传递给其他支持 url scheme 的软件
