### ISSUE TITLE
请教IINA播放器的URL调用参数

### ISSUE THREAD

**Issue by UJohn** [LuckyPuppy514/Play-With-MPV#26]
搜索了一圈没找到怎么设置，有懂的大佬可以教教嘛谢谢

**Comment by LuckyPuppy514** [comment]
1. README 文档，说明用的就是 IINA，已经给了视频参数了，大部分网站应该都可以播放了
2. 其他参数只会影响一部分功能，建议自行查阅 IINA 文档，或者到官方提问
