### ISSUE TITLE
调用mpv播放b站部分视频，音频出现诡异声音

### ISSUE THREAD

**Issue by CBEpt** [LuckyPuppy514/Play-With-MPV#29]
https://www.bilibili.com/video/BV1Mx4y137fa/?vd_source=8fcfe20baf14e7b64e350c3d4241af2f
使用脚本Play-With-MPV：https://github.com/LuckyPuppy514/Play-With-MPV
使用的是tampermonkey，目前仅在这一个视频发现声音有问题？。。。

**Comment by LuckyPuppy514** [comment]
我试了下，跟网页一致，没发现问题，有可能是播放视频没有关闭 mpv 的情况下，又点击播放按钮播放第二个视频，这样的话音频还是第一个视频的音频（mpv 的问题，记得点击右上角的关闭就行）
