### ISSUE TITLE
在b站中js解析出音视频地址后，可以直接使用URLProtocol传到mpv而不需要通过脚本整合

### ISSUE THREAD

**Issue by itKelis** [LuckyPuppy514/Play-With-MPV#3]
可以直接return这个代码将音频和视频同时传到mpv中
`"mpv://--http-header-fields='referer:https://"+ currentDomain+"/','user-agent:" + navigator.userAgent+ "' '"+ currentVideoUrl +"' --audio-file='"+currentAudioUrl + "'";`

**Comment by LuckyPuppy514** [comment]
我试了，的确可以，但是我这里没有mpv://的注册表，你的是安装后就有，还是自己添加的？

**Comment by LuckyPuppy514** [comment]
如果可以，我是打算把所有网站都直接通过 URLProtocol 直接处理了，省一个 powershell 脚本

**Comment by itKelis** [comment]
> 如果可以，我是打算把所有网站都直接通过 URLProtocol 直接处理了，省一个 powershell 脚本

我是linux系统，直接就能打开，windows还要麻烦你写一个注册表
还有我提交了commit,可以看一下

**Comment by LuckyPuppy514** [comment]
好的，感谢，我找时间折腾下

**Comment by itKelis** [comment]
> 好的，感谢，我找时间折腾下

（因为不是专业的，可能代码写的比较烂，还要你整理整理）

**Comment by LuckyPuppy514** [comment]
我也只是个菜鸟，哈哈

**Comment by LuckyPuppy514** [comment]
我这边B站 4K 没问题，你测试的是哪个视频，链接可以发我么

**Comment by LuckyPuppy514** [comment]
已经去除 powersehll 脚本了，windows 没问题，不知道 linux 可不可以，你有空试试

**Comment by itKelis** [comment]
https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/video/videostream_url.md
根据这份文档显示，fnval为0的时候是使用flv格式，是无法传输1080p 60帧以上的格式的，建议设置为1024,因为目前大多数人的显卡还不支持av1硬解。
我自己使用的api是
https://api.bilibili.com/x/player/playurl?otype=json&fourk=1&fnver=0&fnval=1024&avid=302296702&cid=812247318
这个api是音视频分离的，要添加参数。
视频是影视飓风最新的视频 BV1tP41157Jt

**Comment by LuckyPuppy514** [comment]
![image](https://user-images.githubusercontent.com/53246532/186573366-bd1c6a68-92e1-4b61-8f70-bf6a6d723188.png)

1. 我这里都是没问题，前提得登录，你账号支持看什么画质，就能抓到什么画质，现在qn设置的120，够用了，我这个一般是用来看动漫的
2. 你升级最新版，可以直接用么？因为URL Protocol会进行URL编码，有些字符我这边还得自己解码，不知道你的 URL Protocol 行不行，对了你得自行改下 const PWM_PROTOCOL = "PlayWithMPV://";

**Comment by itKelis** [comment]
> ![image](https://user-images.githubusercontent.com/53246532/186573366-bd1c6a68-92e1-4b61-8f70-bf6a6d723188.png)
> 
>     1. 我这里都是没问题，前提得登录，你账号支持看什么画质，就能抓到什么画质，现在qn设置的120，够用了，我这个一般是用来看动漫的
> 
>     2. 你升级最新版，可以直接用么？因为URL Protocol会进行URL编码，有些字符我这边还得自己解码，不知道你的 URL Protocol 行不行，对了你得自行改下 const PWM_PROTOCOL = "PlayWithMPV://";

我改成了mpv: 因为我这里默认是mpv
我用这个api有时候抓不到4k，最高只有1080p 30，也不知道为什么
没关系，我自己改改就行了

**Comment by LuckyPuppy514** [comment]
你的改成 mpv 可以直接用么？

**Comment by itKelis** [comment]
> 你的改成 mpv 可以直接用么？

我这里默认mpv://就是打开mpv的
因为mpv并没有真正官方的二进制版本，官方只提供了源码，网上下载二进制文件的全部都是别人编译放出来的
所以每个人用的版本可能都不太一样，我在linux下载的就自带有mpv://的urlprotocol

**Comment by LuckyPuppy514** [comment]
行，那你先自己改着用，有空我在我虚拟机上试试

**Comment by itKelis** [comment]
> 行，那你先自己改着用，有空我在我虚拟机上试试

好

**Comment by LuckyPuppy514** [comment]
> 

1. 协议名称我也改成 mpv 了
2. B站接口修改了，采用 dash 音视频分离，支持了 8K HDR Dolby Hi-Res 
3. 我在我的 ubuntu 虚拟机安装了 mpv ，但是没有自带协议，不知道你安装的哪个版本 😂

**Comment by itKelis** [comment]
> > 
> 
> 1. 协议名称我也改成 mpv 了
> 2. B站接口修改了，采用 dash 音视频分离，支持了 8K HDR Dolby Hi-Res
> 3. 我在我的 ubuntu 虚拟机安装了 mpv ，但是没有自带协议，不知道你安装的哪个版本 😂

 我用的是arch，直接安装的，我也不知道哈哈哈啊哈，我发现了微软商店里有一个包，是自动注册mpv：//的，github在这:
https://github.com/SilverEzhik/mpv-msix
![image](https://user-images.githubusercontent.com/14844805/190075733-c3c28a6b-83de-45bf-9bd0-b8788a0ee455.png)
![image](https://user-images.githubusercontent.com/14844805/190075762-43237c5f-03c9-41f4-be23-0d9eb5cf5976.png)
