### ISSUE TITLE
今天发现不能看youtube

### ISSUE THREAD

**Issue by SuperBlackWednesday** [LuckyPuppy514/Play-With-MPV#32]
我用的是这个版本 https://github.com/hooke007/MPV_lazy   有冲突吗？

**Comment by LuckyPuppy514** [comment]
不是脚本或播放器问题，是 yt-dlp 的问题，请自行下载最新版并替换 mpv 目录下的 yt-dlp.exe

[yt-dlp/yt-dlp](https://github.com/yt-dlp/yt-dlp/releases)
