### ISSUE TITLE
希望添加对百度网盘网页播放的支持

### ISSUE THREAD

**Issue by Frogsita** [LuckyPuppy514/Play-With-MPV#33]
油猴有个替换为Dplayer的脚本，供参考
https://greasyfork.org/zh-CN/scripts/455103-bd%E7%BD%91%E7%9B%98%E8%A7%86%E9%A2%91%E6%92%AD%E6%94%BE%E5%99%A8

**Comment by LuckyPuppy514** [comment]
大哥，你是在给我挖坑，我看了下这脚本作者，都被逼得封禁了 🤣
这个比普通网页稍微麻烦点，而且即使整好了，维护也麻烦，你看评论就知道了
我建议是，你可以使用：[https://github.com/alist-org/alist](https://github.com/alist-org/alist)
1. 本脚本已经支持 alist , 同时 alist 官方也支持多种播放器
2. 有大佬维护，支持多网盘，而且还可以挂别人分享的东西
3. 你也可以找找别人分享的搭建好的直接使用

![image](https://user-images.githubusercontent.com/53246532/220887006-144dd98d-178d-422a-aa35-efee15d15fe9.png)

**Comment by Frogsita** [comment]
那可以支持直接从上面那个脚本替换后的dplayer里获取吗 两个脚本一起用😥
我主要是想看群组文件的视频 alist好像没法挂这种群组文件😥

**Comment by LuckyPuppy514** [comment]
我稍微看了下，复制链接无法播放，而且即使可以，这样弄我还得同步这个脚本维护（虽然作者被封禁了，不知道还会不会维护）
暂时不会搞了，是坑 🫠

**Comment by Frogsita** [comment]
好吧 谢谢了
