### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by dlupx** [LuckyPuppy514/Play-With-MPV#36]
[ffmpeg] https: HTTP error 403 Forbidden
Failed to open https://xy36x132x218x201xy.mcdn.bilivideo.cn:4483/upgcxcode/97/19
/306731997/306731997-1-30077.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BT
rNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02
J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1
&deadline=1678594330&gen=playurlv2&os=mcdn&oi=1864026216&trid=00006fc47a0fbc3a4d
59aea7336ea900fb28u&mid=53366&platform=pc&upsig=3255d9890f6e6c768ba44db542616e97
&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&mcdnid=1002987&bvc=vod&
nettype=0&orderid=0,3&buvid=708DAE99-9EAB-3A3E-0A19-210398E309B325162infoc&build
=0&agrr=1&bw=114873&logo=A0000001.
[ytdl_hook] ERROR: [generic] None: Unable to download webpage: HTTP Error 403: F
orbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on
https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue t
emplate. Confirm you are on the latest version using  yt-dlp -U
[ytdl_hook] youtube-dl failed: unexpected error occurred

**Comment by LuckyPuppy514** [comment]
这明显是由于没有携带 referer 导致 403，但是脚本会自动携带，你是不是点击的播放历史

**Comment by dlupx** [comment]
> 这明显是由于没有携带 referer 导致 403，但是脚本会自动携带，你是不是点击的播放历史

没

**Comment by dlupx** [comment]
任意视频皆如此

**Comment by LuckyPuppy514** [comment]
那请提供视频链接，脚本设置截图，F12控制台截图

**Comment by dlupx** [comment]
https://www.bilibili.com/video/BV1mv4y1b7hY/?spm_id_from=333.1007.tianma.1-1-1.click  

![image](https://user-images.githubusercontent.com/55268076/224520889-29d1e9cc-2e26-4796-9214-fc937ed1d710.png)

![image](https://user-images.githubusercontent.com/55268076/224520895-13ec28d1-f607-4fb5-9c9b-0b0c309784f6.png)
![image](https://user-images.githubusercontent.com/55268076/224520902-adb0f9c1-11c8-4b1e-99de-59cfb07988e8.png)
![image](https://user-images.githubusercontent.com/55268076/224520908-a50662e1-2e42-454e-917b-805fe86f1920.png)

**Comment by dlupx** [comment]
![image](https://user-images.githubusercontent.com/55268076/224520940-92bb2aca-220d-48c6-8068-70854e2bc8b2.png)

**Comment by LuckyPuppy514** [comment]
请全屏截图，F12，点击控制台截图

**Comment by LuckyPuppy514** [comment]
否则，请你说清楚运行环境，什么系统，什么浏览器

**Comment by LuckyPuppy514** [comment]
看你这图片，我猜你是windows7系统，那可能是不兼容导致的，建议加Q群：921905633 找我远程，我手头没有 windows7 的设备了

**Comment by dlupx** [comment]
win7  edge

**Comment by LuckyPuppy514** [comment]
windows10/11都是没问题的
![image](https://user-images.githubusercontent.com/53246532/224521043-d47c8e92-0e65-44bd-82ca-fb6216bdf596.png)

**Comment by dlupx** [comment]
恩，我win10也没问题

**Comment by LuckyPuppy514** [comment]
那加下Q群：921905633 找我远程，我得看看你控制台的日志

**Comment by dlupx** [comment]
[HKEY_CLASSES_ROOT\mpv\shell\open\command]
@="cmd /V:ON /C \"FOR /F \"tokens=* USEBACKQ\" %%F IN (`C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -STA -command \"Add-Type -AssemblyName System.Web;[System.Web.HTTPUtility]::UrlDecode('%1')\"`) DO (SET param=%%F) & SET param=!param:mpv://=! & start /min D://mpv-lazy//mpv.com !param!\""

修改为

[HKEY_CLASSES_ROOT\mpv\shell\open\command]
@="C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -command & {Add-Type -AssemblyName System.Web;$a=[System.Web.HTTPUtility]::UrlDecode('%1');D:\\mpv-lazy\\mpv.com $a.Trimstart('mpv://')}"

问题解决

**Comment by LuckyPuppy514** [comment]
估计是 win7 的 cmd 版本比较旧，导致命令有问题
我测试都是 win11 测试的，但是用你这个在 win11 上反而会有问题 😂
