### ISSUE TITLE
使用mpv直接播放YouTube报错，但是用你的油猴插件就不报错

### ISSUE THREAD

**Issue by wyx-666** [LuckyPuppy514/Play-With-MPV#37]
- 操作系统：windows10
- 浏览器：chrome 
- 复现问题的操作：
我打开命令行输入：mpv "https://www.youtube.com/watch?v=q9e1Z3LjMlk"
报错如下

[ffmpeg] tcp: Connection to tcp://www.youtube.com:443 failed: Error number -138 occurred
Failed to open https://www.youtube.com/watch?v=q9e1Z3LjMlk.

用你的插件就不报错
我个人感觉就是我的命令行，和你的调用cmd输入不一样导致报错，能否分享一下你调用的命令行，针对YouTube
![image](https://user-images.githubusercontent.com/62326362/224734699-b00a104b-3bc7-4678-bed2-6fb8944baccb.png)

**Comment by wyx-666** [comment]
还是有问题，比如如何控制视频是1K的还是4K的参数，我设置不对，还是希望您可以分享一下命令行

**Comment by wyx-666** [comment]
已经解决了

**Comment by wyx-666** [comment]
好的谢谢，我把这些都写到mpv配置文件里面去了，我发现写到yt-dlp里面会出现问题，写到mpv配置文件里面就没问题，我仔细读了一下错误，发现错误原因是写到yt-dlp配置里面，mpv就会把这些配置选项同视频链接拼接在一起，成一个大的视频链接，显然是错误的，当然写到mpv配置里面就不会出错，逻辑上也没问题，我用的mpv命令行又不是yt-dlp命令行，所以配置文件只能写到mpv命令行里面

如： mpv 视频链接
就可以正常播放了

![image](https://user-images.githubusercontent.com/62326362/224886048-58f371a0-b1cc-4fc4-987b-5d54bbb5259f.png)

可以联系你吗，你可以私信我一个QQ或者其他联系方式，我觉得我的mpv还有很多问题。

**Comment by wyx-666** [comment]
最近发现mpv比其他播放器都简约有着更强的可拓展能力

**Comment by LuckyPuppy514** [comment]
建议用这个，解压就能用，基本不用改什么设置：https://kutt.lckp.top/uVaT3U

**Comment by LuckyPuppy514** [comment]
Q群：921905633
