### ISSUE TITLE
希望增加对TVer和ok.ru的支持

### ISSUE THREAD

**Issue by yuyoiuyoiu** [LuckyPuppy514/Play-With-MPV#38]
https://tver.jp/
（需要日本节点）

https://ok.ru/

**Comment by LuckyPuppy514** [comment]
已添加，[升级到最新版即可](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv)

![image](https://user-images.githubusercontent.com/53246532/224760256-474e3a8a-e833-41f5-a101-0f87326c00ea.png)
