### ISSUE TITLE
日文标题乱码

### ISSUE THREAD

**Issue by yuyoiuyoiu** [LuckyPuppy514/Play-With-MPV#40]
视频链接 ：https://www.youtube.com/watch?v=lOMMFkNuF60
脚本返回：mpv://%22https://www.youtube.com/watch?v=lOMMFkNuF60%22%20--force-media-title=%22(3)%20%E5%B2%A1%E5%B4%8E%E5%B8%82%E3%81%AB%EF%BD%A2%E6%92%AE%E5%BD%B1NG%EF%BD%A3%E3%81%AE%E9%A3%B2%E9%A3%9F%E5%BA%97%E3%80%81%E3%81%AA%E3%81%84%E8%AA%AC%20-%20YouTube%22
显示标题：
![image](https://user-images.githubusercontent.com/61456264/226185374-f96e0c4e-8f1a-4bd1-9a3f-5a67a0aa7d71.png)

![image](https://user-images.githubusercontent.com/61456264/226185159-333323b1-1605-4169-9453-7ec49b20fc47.png)

直接用mpv打开视频链接的话就不会出现乱码
![image](https://user-images.githubusercontent.com/61456264/226185244-59532f89-fd4f-41f4-abbd-7eafccc81a31.png)

**Comment by LuckyPuppy514** [comment]
[升级到最新版再试试](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv)

![20230319234245](https://user-images.githubusercontent.com/53246532/226187382-dae03635-66d4-4c50-a4ae-c3815a8b04c1.gif)
