### ISSUE TITLE
大神，请教个问题，这个插件为什么在本地搭建的alist就能用，服务器搭建的就不能用？服务器想用怎么办？

### ISSUE THREAD

**Issue by SuperBlackWednesday** [LuckyPuppy514/Play-With-MPV#41]
我提供我搭建的一个网站你看看啊，没那个按钮   https://www.goodthings.eu.org/
![uTools_1679953078576](https://user-images.githubusercontent.com/102952892/228072662-d4ca0614-04eb-45b4-9dc3-c7f6995975c6.png)
本地的你应该访问不了 我发个图  但是又那个MPV按钮就非常爽啊 这个要怎么办？

**Comment by LuckyPuppy514** [comment]
第一次进入视频页面，刷新一下应该就会出现了，这个是由于油猴的生效机制导致的
1. 因为每个人的 alist 地址没有统一规范，所以现在采用的匹配正则如下：

```text
// @include                 *://*alist*
// @include                 *://*:5244*
// @match                   *://*/*.mp4
// @match                   *://*/*.mkv
```

2. 如果你的域名符合前两个规则，比如：

`https://alist.xxx.xxx/xxx/xxx/xxx.mp4`

那么，在上一级目录 `https://alist.xxx.xxx/xxx/xxx` 油猴能匹配并生效，所以进入这个链接无需刷新即可生效

如果你的域名不符合前两个规则，比如

`https://www.goodthings.eu.org/xxx/xxx/xxx.mp4`

那么，在上一级目录 `https://www.goodthings.eu.org/xxx/xxx` 油猴不匹配并不生效，导致进入这个链接后还得刷新一次才会生效

**Comment by LuckyPuppy514** [comment]
如果先每次都要刷新麻烦，可以自行添加你的 alist 域名到下方

`https://www.goodthings.eu.org/*`

![image](https://user-images.githubusercontent.com/53246532/228075986-0643d91f-28a8-40f7-87eb-d648180aa08c.png)

![image](https://user-images.githubusercontent.com/53246532/228075845-e4689b9d-7962-4e92-a617-99c9492bf899.png)

**Comment by SuperBlackWednesday** [comment]
不是，我有点懵圈。如果我再解析一个域名，叫alist.goodthings.eu.org  就能生效？

**Comment by LuckyPuppy514** [comment]
> 不是，我有点懵圈。如果我再解析一个域名，叫alist.goodthings.eu.org 就能生效？

看不明白就别看了 🤣，看我发的图片，把你的域名添加进去应该就可以了

**Comment by SuperBlackWednesday** [comment]
![uTools_1679958406064](https://user-images.githubusercontent.com/102952892/228086657-e7585107-222f-4475-b134-ee2ebea7b078.png)
多谢  果然可行
