### ISSUE TITLE
使用体验反馈一下

### ISSUE THREAD

**Issue by yuhouyanran** [LuckyPuppy514/Play-With-MPV#42]
选择用potplayer打开之前总会跳一个cmd窗口，能不能设为隐藏不显示后台自动运行，

**Comment by LuckyPuppy514** [comment]
这个问题有几个人都提过，但是我暂时没有找到很好的办法
1. 基本上都得额外的脚本实现，会增加安装复杂度和出问题的概率
2. 完全隐藏会增加安全风险，杀毒软件也会阻止（头铁可以无视，🤣）
3. 当前只是弹窗一下就隐藏了（我这边基本上1s都不到），其实也不影响后续观看
