### ISSUE TITLE
alist无法调用

### ISSUE THREAD

**Issue by ysysqd** [LuckyPuppy514/Play-With-MPV#43]
测试其他网站可以正常使用。最新版alist，edge已经允许打开播放器了
点击左下角按钮时alist网页播放的视频会暂停，但无法调用播放器，mpv与potplayer都不行

**Comment by LuckyPuppy514** [comment]
阿里云盘亲测没问题，百度不行，其他网盘没做测试

![image](https://user-images.githubusercontent.com/53246532/229324338-2d5c76d7-7ba3-4c5d-b846-f87d6e91800d.png)

![20230402084124](https://user-images.githubusercontent.com/53246532/229324355-fe611776-82f1-406b-a5af-c23960b76923.gif)

**Comment by chengnan049** [comment]
> 阿里云盘亲测没问题，百度不行，其他网盘没做测试
> 
> ![image](https://user-images.githubusercontent.com/53246532/229324338-2d5c76d7-7ba3-4c5d-b846-f87d6e91800d.png)
> 
> ![20230402084124](https://user-images.githubusercontent.com/53246532/229324355-fe611776-82f1-406b-a5af-c23960b76923.gif)
> 

哥，咱看看 Alist 文档吧

**Comment by LuckyPuppy514** [comment]
> > 阿里云盘亲测没问题，百度不行，其他网盘没做测试
> > ![image](https://user-images.githubusercontent.com/53246532/229324338-2d5c76d7-7ba3-4c5d-b846-f87d6e91800d.png)
> > ![20230402084124](https://user-images.githubusercontent.com/53246532/229324355-fe611776-82f1-406b-a5af-c23960b76923.gif)
> >       
> >         [
> >           
> >         
> >             ![20230402084124](https://user-images.githubusercontent.com/53246532/229324355-fe611776-82f1-406b-a5af-c23960b76923.gif)
> >           ](https://user-images.githubusercontent.com/53246532/229324355-fe611776-82f1-406b-a5af-c23960b76923.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/53246532/229324355-fe611776-82f1-406b-a5af-c23960b76923.gif)
> 
> 哥，咱看看 Alist 文档吧

咋了？

**Comment by chengnan049** [comment]
> > > 阿里云盘亲测没问题，百度不行，其他网盘没做测试
> > > ![image](https://user-images.githubusercontent.com/53246532/229324338-2d5c76d7-7ba3-4c5d-b846-f87d6e91800d.png)
> > > ![20230402084124](https://user-images.githubusercontent.com/53246532/229324355-fe611776-82f1-406b-a5af-c23960b76923.gif)
> > >       
> > >         [
> > >           
> > >         
> > >             ![20230402084124](https://user-images.githubusercontent.com/53246532/229324355-fe611776-82f1-406b-a5af-c23960b76923.gif)
> > >           ](https://user-images.githubusercontent.com/53246532/229324355-fe611776-82f1-406b-a5af-c23960b76923.gif)
> > >         
> > >         
> > >           
> > >             
> > >               
> > >             
> > >             
> > >               
> > >               
> > >             
> > >           
> > >           [
> > >             
> > >               
> > >             
> > >           ](https://user-images.githubusercontent.com/53246532/229324355-fe611776-82f1-406b-a5af-c23960b76923.gif)
> > >         
> > >       
> > > ```
> > >     [
> > >       
> > >     
> > >         ![20230402084124](https://user-images.githubusercontent.com/53246532/229324355-fe611776-82f1-406b-a5af-c23960b76923.gif)
> > >       ](https://user-images.githubusercontent.com/53246532/229324355-fe611776-82f1-406b-a5af-c23960b76923.gif)
> > >     
> > >     
> > >       
> > >         
> > >           
> > >         
> > >         
> > >           
> > >           
> > >         
> > >       
> > >       [
> > >         
> > >           
> > >         
> > >       ](https://user-images.githubusercontent.com/53246532/229324355-fe611776-82f1-406b-a5af-c23960b76923.gif)
> > > ```
> > 
> > 
> > 哥，咱看看 Alist 文档吧
> 
> 咋了？

奇怪了我今天看这个问题的时候，问题还是：「百度视频无法播放」，怎么现在变了，奇怪🤔
