### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by sunr1s6** [LuckyPuppy514/Play-With-MPV#44]
- 操作系统：WIN11 谷歌浏览器
- 复现问题的操作：点击b站OR任意支持视频网站，点击播放都没有调出播放器
- 出现的具体问题：设置好播放器，以及网页端设置后，打开任意视频都不会调出播放器。
- 路径参考提示使用\\也没效果，用正常的/ 也没效果 ，
- 配置截图：建议全屏，或浏览器全屏截图
- 报错截图：无报错提示
![Snipaste_2023-04-02_02-50-15](https://user-images.githubusercontent.com/89040381/229309008-6c603d94-e3bb-4305-82a9-99536fd989c9.jpg)

![Snipaste_2023-04-02_02-51-00](https://user-images.githubusercontent.com/89040381/229309038-f11591cb-5afa-4368-bb46-ddb44973c07f.jpg)

**Comment by LuckyPuppy514** [comment]
请尝试先关闭浏览器的其他插件和脚本，再进行设置

**Comment by LuckyPuppy514** [comment]
看你的截图，好像是改了系统字体，改了系统字体千万不要复制软件路径，手动输入
上次有个人就是改了系统字体，还复制，导致下载的注册表问题

**Comment by sunr1s6** [comment]
> 看你的截图，好像是改了系统字体，改了系统字体千万不要复制软件路径，手动输入 上次有个人就是改了系统字体，还复制，导致下载的注册表问题

嗯，我修改了字体，再确认下，路径是使用D:\mpvnet\mpvnet.exe   还是使用D://mpvnet//mpvnet.exe  ?这两种表达式可以一样的效果么？ 还有那个视频编码会影响调起MPV么？  如果用AV1 B站里支持么？我不确定B站是否有AV1的视频。 YouTube好像有。

**Comment by LuckyPuppy514** [comment]
1. 斜杠或反斜杠不影响，会自动转换
2. 编码只对 B站 有效果，会优先抓取选中的编码，但是不一定有，B站也有 AV1 格式的视频
