### ISSUE TITLE
B站无法播放

### ISSUE THREAD

**Issue by NlVEK** [LuckyPuppy514/Play-With-MPV#45]
- 操作系统：windows10
- 浏览器：edge
- 环境：b站
- 复现问题的操作：设置了pot，但是提示找不到视频
- 点回去原视频也播放不了，显示缓冲中，一直缓冲，怀疑是阿b的问题
- 出现的具体问题：
- 配置截图：
![image](https://user-images.githubusercontent.com/40485328/230076807-60a02cbc-ef48-4495-85be-4cba07ba1c57.png)
已经注册过了
- 报错截图：
![image](https://user-images.githubusercontent.com/40485328/230076681-c56c6463-a737-488f-a5e4-ef81618b0478.png)

**Comment by LuckyPuppy514** [comment]
1. 其他网站是否可以播放
2. 请把下载的注册表，用记事本打开，复制贴上来看看

**Comment by NlVEK** [comment]
> 

换成mpv之后能用了
可能是pot的问题，我是两年前的版本
还有自己的一套滤镜啥的

**Comment by LuckyPuppy514** [comment]
有可能，我测试用的 potplayer 版本还是比较新的，不过我其实推荐的是 mpv 😂

**Comment by NlVEK** [comment]
还有想问一下 弹幕的问题，弹幕的文件下下来了放到mpv的script文件夹下没有反应
看了下他那边的主页是说用script-opts传cid 然后调弹幕下载，我这边好像从一开始就没有这个东西

**Comment by LuckyPuppy514** [comment]
如果你是用的我分享的 mpvnet_CM 则不需要单独设置，如果你是自己弄的 mpv ， 则需要自行安装那个 mpv 弹幕脚本，我这个脚本需要设置什么

**Comment by NlVEK** [comment]
>  则需要自行安装那个 mpv 弹幕脚本

好吧我下的是别人的mpv ，我已经把main.lua放到scripts里了但是启动不了 .py

**Comment by LuckyPuppy514** [comment]
..... 你都不看人家脚本安装说明的么，得像我这样放

![image](https://user-images.githubusercontent.com/53246532/230761871-06b437b2-6407-4af2-8c8d-ec5c68929ba2.png)

**Comment by LuckyPuppy514** [comment]
而且如果你本机没有 python 环境，人家打包好了 exe ，会调用 exe 的

**Comment by NlVEK** [comment]
> 而且如果你本机没有 python 环境，人家打包好了 exe ，会调用 exe 的

有Py， 我没仔细看他路径那部分的代码，直接把3个文件放到scirpts里了
不好意思
