### ISSUE TITLE
是否可以增加一个快捷键操作以使播放器打开？

### ISSUE THREAD

**Issue by cing4** [LuckyPuppy514/Play-With-MPV#46]

**Comment by LuckyPuppy514** [comment]
就是代替点击播放按钮么，那应该可以，我找时间加下

**Comment by LuckyPuppy514** [comment]
[v3.4.2 已添加播放快捷键：CTRL + P](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv)
