### ISSUE TITLE
新打包MPV播放画面问题

### ISSUE THREAD

**Issue by KLBin** [LuckyPuppy514/Play-With-MPV#49]
- 操作系统：windows11
- 浏览器：chrome
- 复现问题的操作：bilibili港澳台正常调用脚本打开mpv播放
- MPV版本：https://kutt.lckp.top/Rm4SZN
- 出现的具体问题：相较上个mpv版本曝光度提高了很多，暂停会更高；
- Ps：虽然看博客中你也有这个问题，但是我用上一个版本并不会出现暂停画面变亮（
- 配置截图：
![chrome_eKRJgnkLlb](https://user-images.githubusercontent.com/55175443/232229956-a1a550f7-26b3-4041-a37d-c88591b71e56.jpg)
![mpvnet_KYA793hWju](https://user-images.githubusercontent.com/55175443/232229957-8b9efe1c-b1d0-4f5d-8df8-0a9b8b9da2e3.jpg)
![mpvnet_pEI09Pt1Z2](https://user-images.githubusercontent.com/55175443/232229958-e7441c1a-ed61-4a4c-afb5-54c066def66a.png)
依次分别是原片→mpv播放中→mpv暂停

**Comment by LuckyPuppy514** [comment]
![image](https://user-images.githubusercontent.com/53246532/232230251-c9660b22-8760-4118-80ef-25cb54f7160f.png)

试试这个

**Comment by KLBin** [comment]
![mpvnet_pEI09Pt1Z2](https://user-images.githubusercontent.com/55175443/232230544-939add28-1f57-422c-832f-5755ab85e5c1.png)
打开之后甚至播放也是和暂停一样了:(

**Comment by LuckyPuppy514** [comment]
我这里正常，不太清楚你的什么情况

![image](https://user-images.githubusercontent.com/53246532/232230656-79833f81-3029-4c9f-8e05-e3d3da060fe3.png)

只能远程看看，Q群：921905633
