### ISSUE TITLE
刚刚写了一个小插件， 能全自动加载b站弹幕，能给b站的Protocol添加一个--scripts-opt参数吗

### ISSUE THREAD

**Issue by itKelis** [LuckyPuppy514/Play-With-MPV#5]
可以来试试这个小插件
https://github.com/itKelis/MPV-Play-BiliBili-Comments

就是希望把视频cid改成全局变量，然后传参数的时候把cid传到mpv上，这个小插件就是通过传过来的cid去下载对应的弹幕，然后自动加载字幕到视频上

**Comment by LuckyPuppy514** [comment]
666，我有空试试你这插件

**Comment by LuckyPuppy514** [comment]
可以加下 QQ 122154133 ？我这边弹幕一直提示找不到

![image](https://user-images.githubusercontent.com/53246532/186905364-8f936e57-12e9-4c71-a009-97d7f9fc60c3.png)

**Comment by itKelis** [comment]
> 可以加下 QQ 122154133 ？我这边弹幕一直提示找不到
> 
> ![image](https://user-images.githubusercontent.com/53246532/186905364-8f936e57-12e9-4c71-a009-97d7f9fc60c3.png)

好的

**Comment by itKelis** [comment]
> 666，我有空试试你这插件

cid正确吗

**Comment by itKelis** [comment]
> 可以加下 QQ 122154133 ？我这边弹幕一直提示找不到
> 
> ![image](https://user-images.githubusercontent.com/53246532/186905364-8f936e57-12e9-4c71-a009-97d7f9fc60c3.png)

找到问题了，就是系统问题，windows下路径的斜杠和linux下斜杠是反过来的，导致python得不到路径，正在想办法解决

**Comment by itKelis** [comment]
> 可以加下 QQ 122154133 ？我这边弹幕一直提示找不到
> 
> ![image](https://user-images.githubusercontent.com/53246532/186905364-8f936e57-12e9-4c71-a009-97d7f9fc60c3.png)

程序已经改好了，重新clone一下脚本，然后改一下main.lua和mpv.conf就好了

**Comment by LuckyPuppy514** [comment]
![image](https://user-images.githubusercontent.com/53246532/187220772-e45bdeea-3b5b-4f44-9a67-55a69758c3d2.png)

我这里还是不行

**Comment by itKelis** [comment]
> ![image](https://user-images.githubusercontent.com/53246532/187220772-e45bdeea-3b5b-4f44-9a67-55a69758c3d2.png)
> 
> 我这里还是不行

要看看有没有模块，可以在scripts目录打开命令行单独运行python ./convertAss.py 809097415 看看结果

**Comment by itKelis** [comment]
> ![image](https://user-images.githubusercontent.com/53246532/187222383-d5e64e36-fa44-4924-aa7c-28b181f19801.png)
> 
> 我的 python 直接用的 mpv-lazy 打包好的

你这是刚下的吗

**Comment by LuckyPuppy514** [comment]
报错了，我还得单独装个 python 试试

**Comment by itKelis** [comment]
> 报错了，我还得单独装个 python 试试

他这个python有pip吗，如果装python记得勾选将python路径添加进环境变量

**Comment by itKelis** [comment]
> > 报错了，我还得单独装个 python 试试
> 
> 他这个python有pip吗，如果装python记得勾选将python路径添加进环境变量，然后在命令行先执行pip install requests
看来我把脚本打包成exe更好

**Comment by LuckyPuppy514** [comment]
![image](https://user-images.githubusercontent.com/53246532/187226393-3d29c058-d618-44dd-ac60-f9b67106b471.png)

可以了，看来是 mpv-lazy 打包的 python 少了什么

**Comment by itKelis** [comment]
> ![image](https://user-images.githubusercontent.com/53246532/187226393-3d29c058-d618-44dd-ac60-f9b67106b471.png)
> 
> 可以了，看来是 mpv-lazy 打包的 python 少了什么

那个python应该少了requests 模块

**Comment by LuckyPuppy514** [comment]
嗯，我上传下代码，下次就不用改油猴了

**Comment by itKelis** [comment]
> 嗯，我上传下代码，下次就不用改油猴了

好的，谢谢拉

**Comment by LuckyPuppy514** [comment]
新版本 v1.5.1 发布了，你试试有没有问题

**Comment by LuckyPuppy514** [comment]
提点建议
- python 路径，设置了环境变量，应该可以不用手动设置
- 脚本路径 lua 可以通过：debug.getinfo(1).source 获取，需要截取一下
- subs 建议直接放脚本同级目录，也方便用户找到

这样用户不用手动设置，方便些

**Comment by itKelis** [comment]
> 提点建议
> 
> * python 路径，设置了环境变量，应该可以不用手动设置
> * 脚本路径 lua 可以通过：debug.getinfo(1).source 获取，需要截取一下
> * subs 建议直接放脚本同级目录，也方便用户找到
> 
> 这样用户不用手动设置，方便些

1、有些人不太懂，安装python没有设置环境变量哈哈哈哈，只是为了以防万一
2、脚本路径目前是通过mp.get_script_directory获取的，就是windows要替换一下反斜杠
3、subs放脚本目录也是要手动添加路径的吧

**Comment by LuckyPuppy514** [comment]
mpv-lazy 里面有 python.exe 了，不知道缺了啥，要是能整合进去就方便了

**Comment by itKelis** [comment]
> mpv-lazy 里面有 python.exe 了，不知道缺了啥，要是能整合进去就方便了

应该是缺了requests库，这个虽然说是第三方库，但是用的比较普遍，原始的python大概是没有集成的，我把他改写成urllib应该就可以了，因为linux默认自带python我忽略了这个问题哈哈哈哈

**Comment by itKelis** [comment]
> mpv-lazy 里面有 python.exe 了，不知道缺了啥，要是能整合进去就方便了

但是有一个问题，如果用lazy-mpv自带的python的话，那还是要自己填python路径啊

**Comment by LuckyPuppy514** [comment]
不用，直接使用相对路径就行，mpv-lazy 所有配置都是放在同一个目录下的
![image](https://user-images.githubusercontent.com/53246532/187666828-b1f37b22-cae5-4e79-8b6d-5612e2af225b.png)

**Comment by LuckyPuppy514** [comment]
python.exe 就在 mpv-lazy 目录下
脚本和配置在 mpv-lazy/portable_config 目录下

**Comment by itKelis** [comment]
> python.exe 就在 mpv-lazy 目录下 脚本和配置在 mpv-lazy/portable_config 目录下

好的，我下个mpv-lazy试试

**Comment by LuckyPuppy514** [comment]
我 B 站发了 mpv-lazy + 我这个脚本的教程，如果可以我想把你这个脚本也整进去
https://www.bilibili.com/video/BV1zZ4y1C7kx?spm_id_from=333.999.0.0
mpv-lazy 安装教程也有
https://www.lckp.top/archives/mpv-lazy

**Comment by itKelis** [comment]
> 我 B 站发了 mpv-lazy + 我这个脚本的教程，如果可以我想把你这个脚本也整进去 https://www.bilibili.com/video/BV1zZ4y1C7kx?spm_id_from=333.999.0.0 mpv-lazy 安装教程也有 https://www.lckp.top/archives/mpv-lazy

可以，随便用，反正我这个只是自己做来玩的
