### ISSUE TITLE
求支持两个网站

### ISSUE THREAD

**Issue by SuperBlackWednesday** [LuckyPuppy514/Play-With-MPV#51]
https://www.douyin.com/       https://www.tiktok.com/
这两个网站小姐姐多，大神帮忙把这两个网站加上啊  没有这俩网站 感觉功能缺失一半  
关键是https://live.douyin.com/   https://www.tiktok.com/live/  这两个个域名下的内容 
十分感谢

**Comment by LuckyPuppy514** [comment]
https://www.douyin.com/ 已支持，但是个人感觉体验并不好
其他的需要接口，对接麻烦，暂不考虑
PS：这个脚本主要目的是为了看动漫能够享受 mpv + Anime4K

![20230421210514](https://user-images.githubusercontent.com/53246532/233643499-e49d1d2b-1636-47a3-835c-2d2672ba0131.gif)

**Comment by SuperBlackWednesday** [comment]
好奇怪啊不是看小姐姐用的吗？  你看 https://live.bilibili.com/26309184?session_id=fde7bb03e22031fdf4837e40f517be74_67FA9F47-DA20-4362-8343-41B1A97FCE18&launch_id=1000216&live_from=71001   开启Anime4K  开启5.1声道 效果很有feel  
https://live.douyin.com/806195434240   这个就不行吗 ？ 总感觉少点什么.

**Comment by LuckyPuppy514** [comment]
有毒吧你，Anime4K 是提升动漫画质的，不是提升小姐姐画质的 
![Suggestion](https://user-images.githubusercontent.com/53246532/233656483-95ae38a2-ac0b-4227-a683-3ebf9bcc0b25.gif)

**Comment by SuperBlackWednesday** [comment]
看小姐姐有色度拉升  贼好用  要不大神你也这样设置看看？ 把1234567 挨个开启   想想办法吧大神  就差你的直播接口了。

 Ctrl+1            change-list glsl-shaders toggle "~~/shaders/Anime4K_Deblur_DoG.glsl"            #! 着色器 > 开关 Deblur_DoG.
 Ctrl+2            change-list glsl-shaders toggle "~~/shaders/Anime4K_Denoise_Bilateral_Mode.glsl"              #! 着色器 > 开关 Denoise_Bilateral
 Ctrl+3            change-list glsl-shaders toggle "~~/shaders/Anime4K_Restore_CNN_M.glsl"    #! 着色器 > 开关 Restore_CNN_M
 Ctrl+4            change-list glsl-shaders toggle "~~/shaders/Anime4K_Upscale_GAN_x2_M.glsl" #! 着色器 > 开关 Upscale_GAN_x2_M
 Ctrl+5            change-list glsl-shaders toggle "~~/shaders/Anime4K_AutoDownscalePre_x2.glsl"         #! 着色器 > 开关 AutoDownscalePre
 Ctrl+6            change-list glsl-shaders toggle "~~/shaders/KrigBilateral.glsl"     #! 着色器 > 开关 KrigBilateral
 Ctrl+7            change-list glsl-shaders toggle "~~/shaders/Anime4K_Restore_CNN_L.glsl"      #! 着色器 > 开关 Restore_CNN_L

**Comment by LuckyPuppy514** [comment]
别搞了，我没有找到相应的接口，暂时不会支持的
