### ISSUE TITLE
可以兼容精简b站链接的油猴插件吗

### ISSUE THREAD

**Issue by zdrzdr** [LuckyPuppy514/Play-With-MPV#53]
https://greasyfork.org/zh-CN/scripts/393995-bilibili-%E5%B9%B2%E5%87%80%E9%93%BE%E6%8E%A5
这个插件可以把b站网址后面一串冗长的无意义字符删掉，经过测试和mpv播放冲突

**Comment by LuckyPuppy514** [comment]
1. 本脚本并不篡改原网页的内容，是你用的这个脚本报错导致无法继续执行
2. 可参考修改以下代码，只精简 B 站的链接，而不是所有的链接

![image](https://user-images.githubusercontent.com/53246532/233757001-613cd5df-60d1-4474-bc3c-6645c0e99a0e.png)

```javascript
if(e.destination.url.match(/.*:\/\/.*.bilibili.com\/.*/)){
            const newURL = clean(e.destination.url)
            if(e.destination.url!=newURL) {
                e.preventDefault(); // 返回前还是先阻止原事件吧
                if(newURL == window.location.href) return // 如果清理后和原来一样就直接返回
                // 否则就处理清理后的链接
                window.history.replaceState(window.history.state, "", newURL)
                return
            }
        }
```

**Comment by LuckyPuppy514** [comment]
经测试，是由于改脚本篡改了 window.open 方法导致的，建议让原作者兼容下，你也可以参考下方，修改对应代码即可

![image](https://user-images.githubusercontent.com/53246532/233757532-35bea82c-6dad-4af5-83dd-5a1d58b99f28.png)

```javascript
        if(str.includes('passport.bilibili.com') || !str.match(/.*:\/\/.*.bilibili.com\/.*/))return str;
```

**Comment by zdrzdr** [comment]
> 

好的，多谢！
