### ISSUE TITLE
开始播放后不会自动切换mpv到前台

### ISSUE THREAD

**Issue by zdrzdr** [LuckyPuppy514/Play-With-MPV#54]
- 操作系统：windows10
- 浏览器：chrome
- 出现的具体问题：不知道这个从脚本处可以实现吗，目前播放后是最小化的的需要手动切换到前台

**Comment by LuckyPuppy514** [comment]
mpv 设置置顶即可，在 mpv.conf 中添加以下设置
```text
 ontop = yes
```

**Comment by yayieee** [comment]
我用的是原版mpv，windows10，edge浏览器
确认在mpv.conf里添加了`ontop=yes`，但依然不能默认打开时前台显示，需要手动点一下

**Comment by LuckyPuppy514** [comment]
> 我用的是原版mpv，windows10，edge浏览器 确认在mpv.conf里添加了`ontop=yes`，但依然不能默认打开时前台显示，需要手动点一下

请确保置顶有效，点击 mpv 后，重新点下浏览器，看 mpv 是否仍在顶层，否则就是你的 mpv 置顶设置无效

**Comment by LuckyPuppy514** [comment]
> > 我用的是原版mpv，windows10，edge浏览器 确认在mpv.conf里添加了`ontop=yes`，但依然不能默认打开时前台显示，需要手动点一下
> 
> 请确保置顶有效，点击 mpv 后，重新点下浏览器，看 mpv 是否仍在顶层，否则就是你的 mpv 置顶设置无效

我试了下，最新版的 [mpv-v3](https://sourceforge.net/projects/mpv-player-windows/files/64bit-v3/) 确实无法置顶，临时解决办法是使用 mpv.com 调用，请按下列步骤操作：

修改软件路径后面的 `mpv.exe` 为 `mpv.com` 并保存设置，重新下载注册表并添加

![image](https://user-images.githubusercontent.com/53246532/234320269-a4a42fb5-6580-4895-bbca-11b66d813525.png)

![20230425230751](https://user-images.githubusercontent.com/53246532/234321013-547c6ba0-c6ce-424c-a76f-ce1602e6e250.gif)

**Comment by yayieee** [comment]
通过你所说的操作，我解决了这个问题，非常感谢
