### ISSUE TITLE
Youtube里视频编码设置AV1无效

### ISSUE THREAD

**Issue by Neomanbeta** [LuckyPuppy514/Play-With-MPV#57]
- 操作系统：windows 11 /
- 浏览器：Firefox
- 复现问题的操作：视频编码里设置为AV1
- 出现的具体问题：在观看YouTube的时候，我选择的视频的分辨率下，只有两个编码VP9(HFR)和AV1(HFR)，即时我视频编码里设置了AV1，而且也保存并且导入注册表了，依然播放视频的时候显示视频编码是VP9
- 配置截图：![QQ截图20230426123224](https://user-images.githubusercontent.com/33118244/234470808-f5ec4020-606e-4c9e-b006-bebb4b40c09d.png)
- 报错截图：![QQ截图20230426123330](https://user-images.githubusercontent.com/33118244/234470833-21510895-ab25-4fd6-a76d-3dcb00de2404.png)

**Comment by LuckyPuppy514** [comment]
![image](https://user-images.githubusercontent.com/53246532/234568303-e19ac4c5-21db-430d-855f-bfb6ca5285be.png)

**Comment by Neomanbeta** [comment]
好吧，没看到这个悬浮提示。
