### ISSUE TITLE
新增网站支持请求

### ISSUE THREAD

**Issue by starlight02** [LuckyPuppy514/Play-With-MPV#58]
不知是否能支持[海兔影院](https://www.haitu.tv/vod/type/id/27.html)？个人感觉海兔的动画资源要比其他站高清很多。

**Comment by LuckyPuppy514** [comment]
[已添加，升级到最新版即可](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv)

![image](https://user-images.githubusercontent.com/53246532/235849352-9bf9c7a5-3b02-4c39-b12a-06984d9c6ecd.png)

**Comment by starlight02** [comment]
感谢开发者🥳
