### ISSUE TITLE
请问我在使用过程中无法获取播放列表是什么原因，bilibili和低端影视都只能获取p1

### ISSUE THREAD

**Issue by Bergmott** [LuckyPuppy514/Play-With-MPV#6]

**Comment by Bergmott** [comment]
![image](https://user-images.githubusercontent.com/98070516/187891155-52f864d7-a740-48f4-b74f-1c4530d4eb77.png)

![5745d594a3bf095e2d2b8da3d3f2ffd](https://user-images.githubusercontent.com/98070516/187891176-ec7af339-b818-4dd8-aaaa-2c94eb5c4e6a.jpg)
![7e29543828a220da549e416f8d93fef](https://user-images.githubusercontent.com/98070516/187891311-cc1c041d-e5e4-4baf-86da-965160f4dc75.jpg)

**Comment by LuckyPuppy514** [comment]
正常的，因为获取的是当前网页的视频链接，暂时不支持获取整个列表，抱歉
