### ISSUE TITLE
希望能支持几个没言论审核的视频站点

### ISSUE THREAD

**Issue by aries1998** [LuckyPuppy514/Play-With-MPV#60]
这几个希望有可能支持一下，油管早已成为宣传机器。
https://odysee.com/
https://rumble.com/
https://www.bitchute.com/

**Comment by LuckyPuppy514** [comment]
[已添加，升级到最新版即可](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv)

**Comment by aries1998** [comment]
哇，光速，感谢感谢
