### ISSUE TITLE
youtube不能正常加载

### ISSUE THREAD

**Issue by sqq135** [LuckyPuppy514/Play-With-MPV#61]
win11
edge
youtube
油管不能正常使用，网页版正常播放，点击mpv也可以调用，但是mpv不能加载。哔哩哔哩（和其他）正常使用
配置 i5-13500H
怀疑是油管没有走代理，但开全局mpv仍不行。（甚至标题都没有显示）
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/78015121/672813d7-c52c-482e-879b-1cc07036d1a0)

**Comment by sqq135** [comment]
如果打开clash并且在设置里加上代理可以，但是我用的是路由器小飞机，应该怎么加呢

**Comment by LuckyPuppy514** [comment]
> 如果打开clash并且在设置里加上代理可以，但是我用的是路由器小飞机，应该怎么加呢

旁路由网关的方式科学，不需要设置代理，如果不行，可以尝试开启 socks / http 服务端，然后填写对应的代理地址

**Comment by sqq135** [comment]
感谢，是的，只要开科学，填代理地址就可以了，但是网页正常加载，mpv却得专门开服务端，感觉有点繁琐。并且填上代理地址之后，其他网页（不需要翻墙）也不会自动删除，是否可以识别地址自动填写代理。
小小建议，希望能更好。
&nbsp;


shi
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月12日(星期五) 中午11:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LuckyPuppy514/Play-With-MPV] youtube不能正常加载 (Issue #61)





  
如果打开clash并且在设置里加上代理可以，但是我用的是路由器小飞机，应该怎么加呢
  
旁路由网关的方式科学，不需要设置代理，如果不行，可以尝试开启 socks / http 服务端，然后填写对应的代理地址

**Comment by LuckyPuppy514** [comment]
路由器网关的方式，是不需要设置的，我就是这样用，你的不可以应该是你的设置有问题
windows 的 clash客户端，则必须手动设置，js 应该是做不到读取电脑上的代理设置的

**Comment by sqq135** [comment]
发现又可以了，可能是我用来测试那个视频太大，之前那个节点没选好，现在又可以了。
抱歉因为无端的原因打扰了。
另外，左下角的图标着实不太好看（mpv一系也都一般），有没有要更改ui的日程？
&nbsp;


shi
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月12日(星期五) 中午11:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LuckyPuppy514/Play-With-MPV] youtube不能正常加载 (Issue #61)





 
路由器网关的方式，是不需要设置的，我就是这样用，你的不可以应该是你的设置有问题
 windows 的 clash客户端，则必须手动设置，js 应该是做不到读取电脑上的代理设置的

**Comment by LuckyPuppy514** [comment]
图标先这样吧，能用就行，🤣
