### ISSUE TITLE
[feat req] 向localhost直接发送http request传输相关数据

### ISSUE THREAD

**Issue by NeumoNeumo** [LuckyPuppy514/Play-With-MPV#65]
作者您好，感谢您制作如此方便的插件。

然而，在linux上使用时，我遇到一些玄学问题：由x-scheme-handler触发执行的代码在调用mpv时会报错`mpv: symbol lookup error: mpv: undefined symbol: vkcreatexlibsurfacekhr`。尝试了切换环境变量、显式指定动态链接库、重装vulkan，均无果。再之后甚至连x-scheme-handler都无法被触发了。

请不要紧张，这不是请求您帮忙定位问题的issue。事实上，这种黑箱问题是确实是十分难以解决的。因此我希望能够**存在另一种方式实现网页端与本机的通信，那种方式更为可控，且更具有操作系统可移植性。**

具体来说，是在本地运行一个daemon进程监听某个端口，e.g. 1234，而网页端向 localhost:1234 发送请求，请求内容即是`Play-With-MPV` 解析到的数据，包括视频url，字幕 url 等等。

您的代码主要需要修改、增加的地方：GUI上添加一个新的可选项`http request`，与文本框`port`，逻辑部分则需要根据前两个对象的结果判断是发送mpv://还是向http://localhost:1234发送请求。

如果您愿意实现，我可以为您的repo写一个本地的 node/python/cpp server。这取决于您对哪个语言更熟悉（但是我水平比较一般，写出来的代码可能并不能保证绝对安全与高效）。

**Comment by LuckyPuppy514** [comment]
1. 其实已经有类似的项目，比如：[https://github.com/videoanywhere/playwithmpv](https://github.com/videoanywhere/playwithmpv)，我还没写这个项目的时候也尝试使用过，但是安装较为麻烦，而且还得额外运行一个服务端
2. 你的问题应该可以通过修改 x-scheme-handler 协议（实在不行可以自行写个脚本修正参数），我记得有用户在 linux 上成功使用的，他好像用的是 [mpv.io](https://mpv.io/) 这个版本，自带的 x-scheme-handler 协议

**Comment by NeumoNeumo** [comment]
1.
> 其实已经有类似的项目，比如：[videoanywhere/playwithmpv](https://github.com/videoanywhere/playwithmpv)，我还没写这个项目的时候也尝试使用过，但是安装较为麻烦，而且还得额外运行一个服务端

如果“安装麻烦“指的是需要额外安装python/node或自己编译cpp，那么是的；额外一个服务端，也是的。但在windows下修改注册表其实也是一件“安装麻烦”的事情，只是这步被您的程序自动化了。额外的一个服务端的好处正如我上面所述：
>网页端与本机的通信，那种方式更为可控，且更具有操作系统可移植性

**另外，这种连接方式是可选的，windows下的用户依然可以沿用您当前的方式。**

2. 
> 你的问题应该可以通过修改 x-scheme-handler 协议（实在不行可以自行写个脚本修正参数）

是的，事实上我昨天已经写了，但就是卡在无法从x-scheme-handler触发的shell中运行mpv（见我最上面那条回复的第一句话）。也确实在linux上成功使用的，我在该repo之前的issue中也看到过，例如[这条](https://github.com/LuckyPuppy514/Play-With-MPV/issues/3)。但是linux的desktop问题千千万，在昨天反复折腾后情况反而变得更糟了，遂停止折腾。

> 他好像用的是 [mpv.io](https://mpv.io/) 这个版本，自带的 x-scheme-handler 协议

a) mpv.io就是原版mpv，我用的也是，而且还是build from source的最新版。b) mpv并没有提供x-scheme-handler协议，因为[作者认为这会导致安全问题](https://github.com/mpv-player/mpv/issues/7985#issuecomment-670677096)（该链接中的方案我也试过，但结果还是「我最上面那条回复的第一句话」，猜测是由apt安装vulkan缺失部分内容，但不想再折腾了）。另，上文的x-scheme-handler处理的mpv协议就是我自定义的。

**我临时写了一个实现**：https://github.com/LuckyPuppy514/Play-With-MPV/compare/main...NeumoNeumo:Play-With-MPV:main （服务端使用 `node play-with-mpv-d.js` 开启，默认使用环境变量中的 `mpv` 路径，如果没有设置环境变量，也可以修改`play-with-mpv-d.js`文件的 path_to_mpv 指向 mpv 可执行文件）但这个实现还没有修改前端UI，这取决于您是否认为该特性是有意义的，如果您觉得这是无意义的，那我就只需要自己能用就行了。

**Comment by LuckyPuppy514** [comment]
我个人比较少用 Linux 桌面端，一般也就是虚拟机用用，而且当初就是为了简化，没有考虑这种需要服务端的模式，所以暂时不会添加，不过我觉得应该还是修改 x-scheme-handler 比较简单，我有空在 ubuntu 上试试 😂
