### ISSUE TITLE
https://www.lckp.top/common/bilibili/jsonToSrt/ 解析错误

### ISSUE THREAD

**Issue by NeumoNeumo** [LuckyPuppy514/Play-With-MPV#66]
症状：[该视频](https://www.bilibili.com/video/BV1eL411m78q) 字幕无法正常播放，出现时而字幕不出现，时而扎堆的情况。

![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/107997665/4216355c-e06a-4071-853b-47c25e9ed661)

原因：b站字幕文件为[该json文件](https://aisubtitle.hdslb.com/bfs/subtitle/0a22bc78060061e4108e458fc1808d9a94e7d4ff.json?auth_key=1684337896-7f7f639b67f44e1685117ee976ef07ee-0-1d13331e4269d3dba9ef12195871812e&lan=zh-Hans)（可能已失效）
```json
{"body":[{"from":0.2,"to":1.8,"location":0,"content":"对于类似电脑初学者这类"},
{"from":1.8,"to":2.933,"location":0,"content":"对性能要求不高"},
{"from":2.933,"to":5.333,"location":0,"content":"对响应速度感知也不太强的用户来说"},
{"from":5.466,"to":6.766,"location":0,"content":"当今市面上的产品"},
{"from":6.766,"to":8.333,"location":0,"content":"可以说是性能完全过剩"},
{"from":8.333,"to":9.499,"location":0,"content":"而他们的需求"},
{"from":9.7,"to":11.733,"location":0,"content":"或许一个电视盒子就够了"},
{"from":18.9,"to":20.533,"location":0,"content":"这次用来改装的电视盒子"},
{"from":20.533,"to":23.4,"location":0,"content":"其核心为晶晨的S905L3A"},
{"from":23.4,"to":25.266,"location":0,"content":"64位4核A53"},
...
```
然而传到https://www.lckp.top/common/bilibili/jsonToSrt/解析的结果为
```text
1
00:00:00,20 --> 00:00:01,80
对于类似电脑初学者这类

2
00:00:01,80 --> 00:00:02,9330
对性能要求不高

3
00:00:02,9330 --> 00:00:05,3330
对响应速度感知也不太强的用户来说

4
00:00:05,4660 --> 00:00:06,7660
当今市面上的产品

5
00:00:06,7660 --> 00:00:08,3330
可以说是性能完全过剩

6
00:00:08,3330 --> 00:00:09,4990
而他们的需求

...
```
注意字幕3，毫秒位最低有效位多了个0。将末尾的0去除后，字幕播放正常。

**Comment by LuckyPuppy514** [comment]
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/656c2844-72fc-454a-bd97-e65508c35ac4)
