### ISSUE TITLE
又发现一个问题

### ISSUE THREAD

**Issue by WuYang09661** [LuckyPuppy514/Play-With-MPV#69]
油管的直播通过mpv.net cm看不了，视频也看不了 （可能是我没配置好（视频软件代理需要设置？））

**Comment by LuckyPuppy514** [comment]
如果看不了，一般就两种情况

1. 网络问题，windows 下的 clash / v2rayN 等软件，需要手动设置代理
2. mpv 中 yt-dlp 不是最新版，自行 [更新到最新版](https://github.com/yt-dlp/yt-dlp/releases)；或者没有设置好，自行解决或者 [下载我打包的版本](https://kutt.lckp.top/uVaT3U)

![20230521092413](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/5a6017a5-c1e1-41b3-bce0-a5b6a85ed2cd)
