### ISSUE TITLE
[bug] bilibili视频未正常获取网页标题

### ISSUE THREAD

**Issue by dyphire** [LuckyPuppy514/Play-With-MPV#7]
youtube使用脚本可正常获取并传递网页标题，bilibili使用脚本未能正常获取到网页标题
其他支持站点未测试
![image](https://user-images.githubusercontent.com/61936050/188362566-5ee0332a-5bbc-4da1-b4b1-15797fa98b26.png)

**Comment by LuckyPuppy514** [comment]
正常哈，改版了，把 powershell 脚本去掉了，只有注册表信息，所以没法传中文标题过去（会被URL编码，暂时没法解码）

**Comment by LuckyPuppy514** [comment]
原来 powershell 脚本是可以的，但是安装起来麻烦，还容易出问题

**Comment by dyphire** [comment]
不能获取传递标题的话有点不便，因为会在我的历史记录脚本菜单里出现一堆www.bilibili.com的垃圾信息。

希望后面能找到方法解决，这个脚本支持解析b站会员视频还是值得好评的

**Comment by LuckyPuppy514** [comment]
我有空研究研究（不过注册表里面代码没法写那么多，别抱太大希望 QAQ）

**Comment by LuckyPuppy514** [comment]
搞定了，油猴脚本升级到最新版 v1.5.2，然后重新：[添加一下注册表信息](https://github.com/LuckyPuppy514/Play-With-MPV#4-%E6%B7%BB%E5%8A%A0%E6%B3%A8%E5%86%8C%E8%A1%A8%E4%BF%A1%E6%81%AF)  

![image](https://user-images.githubusercontent.com/53246532/188429817-91af5fc3-bcd0-4846-a548-83aa2f235ec2.png)

**Comment by dyphire** [comment]
确实，新版本b站可以正常获取到标题了
