### ISSUE TITLE
左下角的按钮不会自动隐藏

### ISSUE THREAD

**Issue by 1353604736** [LuckyPuppy514/Play-With-MPV#70]
- 操作系统：windows7 / windows10/11 / ...
- 浏览器：chrome / edge / ...
- 复现问题的操作：https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv/discussions/181074#comment-395515
- 出现的具体问题：出现了什么情况
- 配置截图：https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv/discussions/181074#comment-395515
- 报错截图：https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv/discussions/181074#comment-395515

**Comment by LuckyPuppy514** [comment]
[请不要重复提问，本问题答复见 greasyfork.org](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv/discussions/181074#comment-395515)
