### ISSUE TITLE
win10 3.6.0

### ISSUE THREAD

**Issue by Fast12138** [LuckyPuppy514/Play-With-MPV#72]
系统：win10 LTSC
脚本：3.6.0
播放器：potplayer

配置完成，安装注册表完成。点击play cmd闪现，播放器没反应。直接降级到3.5.7可以使用。第一次使用。没有log提供

**Comment by LuckyPuppy514** [comment]
[请按模板格式重新提 issue](https://github.com/LuckyPuppy514/Play-With-MPV/issues/new?assignees=&labels=&projects=&template=%E9%97%AE%E9%A2%98%E5%8F%8D%E9%A6%88.md&title=)
