### ISSUE TITLE
网站支持及失效修复请求

### ISSUE THREAD

**Issue by starlight02** [LuckyPuppy514/Play-With-MPV#73]
请求支持：
- [Animoe动漫](https://animoe.org)

以下站点目前已失效，请求修复：
- https://www.mgnacg.com （无法正确获取视频）
- https://www.mengfan.tv （无法显示按钮）
- https://www.anfuns.cc （无法显示按钮）

**Comment by LuckyPuppy514** [comment]
- https://animoe.org 暂时无法支持
- https://www.mgnacg.com 已修复
- https://www.mengfan.tv 已修复
- https://www.anfuns.cc 已修复（但是大部分已经无法支持，不推荐使用了）

**Comment by starlight02** [comment]
感谢作者，真乃神速👍
