### ISSUE TITLE
请求增加支持 pikpak

### ISSUE THREAD

**Issue by Jadaff** [LuckyPuppy514/Play-With-MPV#74]
请问作者能否增加支持 pikpak ：[https://mypikpak.com/drive/all](https://mypikpak.com/drive/all)，非常感谢

**Comment by LuckyPuppy514** [comment]
[v3.6.3 已支持](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv?version=1203634)

![20230611214043](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/1895a9ae-2234-49c6-8690-2ab2cbe6de0b)

**Comment by Jadaff** [comment]
感谢！
