### ISSUE TITLE
不能使用

### ISSUE THREAD

**Issue by Galahahad** [LuckyPuppy514/Play-With-MPV#77]
注册表配置完毕后，点击播放后有一个蓝色Powershell框闪出后消失，然后就没有反应了。

**Comment by LuckyPuppy514** [comment]
[请按模板格式提问](https://github.com/LuckyPuppy514/Play-With-MPV/issues/new?assignees=&labels=&projects=&template=%E9%97%AE%E9%A2%98%E5%8F%8D%E9%A6%88.md&title=)

**Comment by LuckyPuppy514** [comment]
请按模板说清楚后，自行重开
