### ISSUE TITLE
b站没有弹幕是少弄了什么吗

### ISSUE THREAD

**Issue by liJie-wk** [LuckyPuppy514/Play-With-MPV#78]
- 操作系统：windows11
- 浏览器：edge

![屏幕截图_20230503_224705](https://github.com/LuckyPuppy514/Play-With-MPV/assets/57932868/f29f91fa-8ccb-4d03-ab79-ad5fdba2b9ed)

**Comment by liJie-wk** [comment]
2. B站自动生成的字幕可以默认关闭吗？因为大部分视频都内嵌了字幕。
3. 能否支持pikpak？
问题有点多，一起问了，抱歉

**Comment by LuckyPuppy514** [comment]
**请不要多个问题一起，既不方便处理，又不方便后续的人查找相关问题**

1. 关于弹幕，教程中明确提醒，非我分享的 mpv.net_CM 部分功能无法使用，其中就包括B站弹幕功能，因为B站弹幕功能是 mpv 脚本，如果不是使用我分享的 mpv，请自行安装
2. 请在设置中自行关闭字幕功能
![20230624074300](https://github.com/LuckyPuppy514/image/raw/main/2023/2023-06-24/20230624074300.webp)
3. 问题重复：[#74](https://github.com/LuckyPuppy514/Play-With-MPV/issues/74)

**Comment by liJie-wk** [comment]
好的，明白了，感谢！好人一生平安
