### ISSUE TITLE
不能使用

### ISSUE THREAD

**Issue by Galahahad** [LuckyPuppy514/Play-With-MPV#79]
- 操作系统：windows10
- 浏览器：chrome.
- 复现问题的操作：感觉比较难复现
- 出现的具体问题：配置注册表后，重启浏览器，进入播放页面，会有非常短的Powershell蓝色框弹出，然后迅速消失
- 配置截图：
- z690-a，12600KF，3080
- 报错截图：弹窗消失的速度过快，无法截图

**Comment by LuckyPuppy514** [comment]
求求你认真按模板要求写清楚问题，要的是脚本的配置截图，不是你的电脑配置

**Comment by Galahahad** [comment]
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/61223137/d6199494-ae10-4bcc-b879-0e9c96557b93)
麻烦了

**Comment by LuckyPuppy514** [comment]
再提供一下 mpv 安装目录的截图，还有把下载的注册表内容贴上来

**Comment by Galahahad** [comment]
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/61223137/ae8a1a01-7247-423d-ae91-fc707c05175b)
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome]
"ExternalProtocolDialogShowAlwaysOpenCheckbox"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge]
"ExternalProtocolDialogShowAlwaysOpenCheckbox"=dword:00000001

[HKEY_CLASSES_ROOT\mpv]
@="mpv Protocol"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\mpv\DefaultIcon]
@=""

[HKEY_CLASSES_ROOT\mpv\shell]
@=""

[HKEY_CLASSES_ROOT\mpv\shell\open]
@=""

[HKEY_CLASSES_ROOT\mpv\shell\open\command]
@="C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -WindowStyle Hidden -Command \"& {Add-Type -AssemblyName System.Web;$PARAMS=([System.Web.HTTPUtility]::UrlDecode('%1') -replace '^mpv://'); Start-Process -FilePath \\\"‪D://SOFTWARE//MPV//mpv.exe\\\" -ArgumentList $PARAMS}\""

**Comment by LuckyPuppy514** [comment]
你截图的路径，和你填的路径 `‪D://SOFTWARE//MPV//mpv.exe` 明显不符合啊

**Comment by LuckyPuppy514** [comment]
而且，为何你的 mpv-lazy 里面还有 mpvnet.exe，怎么乱七八糟的

**Comment by Galahahad** [comment]
几个版本的mpv在切着用，所以有点乱。
然后切回正常的mpv-lazy后，
但还是一样的效果。
有点难受

**Comment by LuckyPuppy514** [comment]
你怎么答非所问，乱是一方面，主要是你填的路径，跟你截图的路径完全不一致啊

**Comment by LuckyPuppy514** [comment]
请改正软件路径，保存设置，重新下载注册表并添加

**Comment by Galahahad** [comment]
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/61223137/fb9f3366-0842-4e19-acc8-2b24a6b67c99)
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome]
"ExternalProtocolDialogShowAlwaysOpenCheckbox"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge]
"ExternalProtocolDialogShowAlwaysOpenCheckbox"=dword:00000001

[HKEY_CLASSES_ROOT\mpv]
@="mpv Protocol"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\mpv\DefaultIcon]
@=""

[HKEY_CLASSES_ROOT\mpv\shell]
@=""

[HKEY_CLASSES_ROOT\mpv\shell\open]
@=""

[HKEY_CLASSES_ROOT\mpv\shell\open\command]
@="C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -WindowStyle Hidden -Command \"& {Add-Type -AssemblyName System.Web;$PARAMS=([System.Web.HTTPUtility]::UrlDecode('%1') -replace '^mpv://'); Start-Process -FilePath \\\"‪D://SOFTWARE//MPV//mpv-lazy//mpv.exe\\\" -ArgumentList $PARAMS}\""
已经更改路径，下面是注册表的具体内容，症状还是没有变化

**Comment by LuckyPuppy514** [comment]
1. 请问你下载后是否重新添加注册表了？
2. 如果已经添加，建议重新找一个干净的目录，重新安装 mpv，不要把各个版本的 mpv 混在一个目录

**Comment by LuckyPuppy514** [comment]
如果还是解决不了，加Q群：921905633，找我远程

**Comment by Galahahad** [comment]
看了一下注册表，找到问题了，
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/61223137/8c6370b5-5cd0-4f76-ae2e-cd51924a6709)
图中路径的字母“D”出现了乱码，将其改正后可以正常工作了，不太清楚为什么会出现乱码

**Comment by LuckyPuppy514** [comment]
这是很可能是因为你改了系统字体，然后又从系统属性或文件资源管理器地址栏直接复制导致的，一般手动输入即可

在这个网站：[URL编码](http://www.jsons.cn/urlencode)，进行URL编码即可看出区别

你输入的 D，编码后是 `%E2%80%AAD`

正常输入的 D，编码后是 `D`
