### ISSUE TITLE
请问能否支持下巴哈？

### ISSUE THREAD

**Issue by Silverhza** [LuckyPuppy514/Play-With-MPV#8]
如题

**Comment by LuckyPuppy514** [comment]
1. 巴哈好像没接口
2. 巴哈有权限验证

只能试试网页抓取，还得解决权限的问题，我有空研究研究，不过别抱太大希望 🤣

**Comment by LuckyPuppy514** [comment]
最新版已支持：https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv
> 我没有会员，所以只能看720p，你要是有会员，麻烦帮忙测试下，然后通知我一声 🤣

![](https://cdn.jsdelivr.net/gh/LuckyPuppy514/pic-bed/common/gamer_tuya.jpg)

**Comment by Silverhza** [comment]
测试成功！感谢大佬！

**Comment by Silverhza** [comment]
1080P可以观看。

**Comment by LuckyPuppy514** [comment]
那就行，好用也麻烦给颗小星星 🌟，感谢 😘
