### ISSUE TITLE
[3.6.6][B站] 直播流画质

### ISSUE THREAD

**Issue by raytracesoak** [LuckyPuppy514/Play-With-MPV#80]
似乎插件未能获取到B站直播流的最高画质（原画/原画PRO），无论我怎么设置最高只能到blueray（蓝光）。
请帮忙看下是我哪里没设置对还是流解析需要调整。

![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/18105970/92486dfd-5664-4a8b-8876-22f5cfe956ed)
原画流是hevc
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/18105970/7ad7e8aa-783c-4268-9cd6-794f2e4f576a)

![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/18105970/3d8fdfe2-538a-446e-bb28-e0812448d0ec)

MPV
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/18105970/2a136d5d-5814-4d22-a3c4-77d54f0ee214)

![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/18105970/ea11e87f-da1d-4054-95b9-16db1cb7784c)

**Comment by LuckyPuppy514** [comment]
测试直播间：https://live.bilibili.com/108291

抓取时接口返回信息，current_qn = 4，qn = 4 就是原画，没有问题

```text
{
  "code": 0,
  "message": "0",
  "ttl": 1,
  "data": {
    "current_quality": 4,
    "accept_quality": [
      "4",
      "3"
    ],
    "current_qn": 4,
    "quality_description": [
      {
        "qn": 4,
        "desc": "原画"
      },
      {
        "qn": 3,
        "desc": "高清"
      }
    ],
    "durl": [
      {
        "url": "https://cn-gddg-ct-01-14.bilivideo.com/live-bvc/911278/live_17467811_3772317_bluray.flv?expires=1687780034&pt=&deadline=1687780034&len=0&oi=1903512126&platform=&qn=10000&trid=10009991876d2cc841d496aae4ad689d993d&uipk=100&uipv=100&nbs=1&uparams=cdn,deadline,len,oi,platform,qn,trid,uipk,uipv,nbs&cdn=cn-gotcha01&upsig=119fee2457416f5b48f52dfb8e40dff3&sk=bb54a0d1f51eef6cba7c72ca02291d6f&p2p_type=0&sl=2&free_type=0&mid=356927809&sid=cn-gddg-ct-01-14&chash=1&bmt=1&sche=ban&score=11&pp=rtmp&source=one&trace=891&site=c7f668565c15a79e5f5f60cab637dc96&order=1",
        "length": 0,
        "order": 1,
        "stream_type": 0,
        "p2p_type": 0
      }
    ]
  }
}
```

网页原画是1080p，超清PRO是720p，mpv 播放的显示是1080p没问题

你这个问题，是你只看到编码方式，不看格式，网页播放视频格式是 mp4，但是接口拿到的是 flv，所以编码方式有差异

**Comment by LuckyPuppy514** [comment]
网络有点问题，上传不了截图，但是亲测应该是没有问题的

**Comment by raytracesoak** [comment]
那看来是编码和这个"bluray.flv"误导了我，我还以为写着bluray就是蓝光呢。感谢解答。
