### ISSUE TITLE
低端影视失效了，无法播放，望修复

### ISSUE THREAD

**Issue by zzyyi66** [LuckyPuppy514/Play-With-MPV#81]
- 操作系统：windows7 / windows10/11 / ...
- 浏览器：chrome / edge / ...
- 复现问题的操作：点击哪里
- 出现的具体问题：出现了什么情况
- 配置截图：建议全屏，或浏览器全屏截图
- 报错截图：建议全屏，或浏览器全屏截图

**Comment by LuckyPuppy514** [comment]
[v3.6.7 已修复](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv?version=1212681)

![20230629211339](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/2d9ebd32-69c4-4bf3-a3c9-9fd2e788985c)

**Comment by zzyyi66** [comment]
牛！牛！牛！
