### ISSUE TITLE
只能每一集就开启一个新的MPV?

### ISSUE THREAD

**Issue by mn12345678910** [LuckyPuppy514/Play-With-MPV#82]
- 操作系统 windows11
- 浏览器：Firefox 114.0.2
- 复现问题的操作：播放影片
- 出现的具体问题：總是會開啟新的MPV
- 配置截图：![圖片](https://github.com/LuckyPuppy514/Play-With-MPV/assets/38092860/9b798ad5-6f9e-4c71-91b0-c1e91d66f21d)
想请问是否能从头到尾都只使用一个MPV而不使用新的MPV?
每次看完一集就得关掉视窗然后在切到新开启的MPV上
![圖片](https://github.com/LuckyPuppy514/Play-With-MPV/assets/38092860/f564298a-0d08-444e-a6ef-64c9fbeeb5be)

**Comment by LuckyPuppy514** [comment]
mpvnet 的话，可以在 mpv 选项设置中开启单线程模式即可，mpv 的话你得自己找下相关设置（我暂时没找到）

![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/7ae8a4a2-4552-4e66-a5f3-9f10e773afd7)

**Comment by mn12345678910** [comment]
谢谢 我搜寻了一下似乎是Windows系统特有的问题
我找到了一个解决方法:https://github.com/SilverEzhik/umpvw
但似乎没办法支持Play-With-MPV
![圖片](https://github.com/LuckyPuppy514/Play-With-MPV/assets/38092860/16b09c12-5b8a-4272-906e-f6e94d661b49)

请问有可能从您这边处理吗?

**Comment by LuckyPuppy514** [comment]
这不是脚本的问题，没办法实现

**Comment by mn12345678910** [comment]
好的 我改用MPV.NET就行
