### ISSUE TITLE
刪除

### ISSUE THREAD

**Issue by NBurger500** [LuckyPuppy514/Play-With-MPV#83]

**Comment by LuckyPuppy514** [comment]
[请认真看文档，其他播放器只能自己找相关文档](https://github.com/LuckyPuppy514/Play-With-MPV#43-%E8%87%AA%E5%AE%9A%E4%B9%89)

`视频参数` 可以尝试使用 `mpc://${videoUrl}` 或 `mpc://${EvideoUrl}`

其他参数自己查找播放器相关文档，如果不填，鼠标放到上面会有对应的说明
