### ISSUE TITLE
不显示插件按钮

### ISSUE THREAD

**Issue by wuhonhyu** [LuckyPuppy514/Play-With-MPV#89]
susudyy. com，susudm8. com左下角都没有插件按钮

**Comment by LuckyPuppy514** [comment]
[v3.7.6 已修复](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv?version=1223991)

![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/d5923b7e-f59b-4fd3-817d-5e3d0db95ff1)
