### ISSUE TITLE
无法拉起mpvnet

### ISSUE THREAD

**Issue by xwym711** [LuckyPuppy514/Play-With-MPV#90]
- 操作系统：windows11
- 浏览器：chrome 与 edge 
- 复现问题的操作：保存打开注册表后，点击左下角播放图标，点击 打开 Windows Powershell 无法拉起应用，视频会暂停播放
- 出现的具体问题：点击 打开 Windows Powershell 无法拉起应用，视频会暂停播放
- 配置截图：
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/140372472/670fb26f-6b12-46e4-b6c9-318c6a3a508e)
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/140372472/58b10677-48c9-43d4-8de3-f7a64189c100)
- 报错截图：建议全屏，或浏览器全屏截图
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/140372472/40b6b85e-5176-45dc-89cb-5e529ca20019)

**Comment by xwym711** [comment]
注册表
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome]
"ExternalProtocolDialogShowAlwaysOpenCheckbox"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge]
"ExternalProtocolDialogShowAlwaysOpenCheckbox"=dword:00000001

[HKEY_CLASSES_ROOT\mpv]
@="mpv Protocol"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\mpv\DefaultIcon]
@=""

[HKEY_CLASSES_ROOT\mpv\shell]
@=""

[HKEY_CLASSES_ROOT\mpv\shell\open]
@=""

[HKEY_CLASSES_ROOT\mpv\shell\open\command]
@="C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe -WindowStyle Hidden -Command \"& {Add-Type -AssemblyName System.Web;$PARAMS=([System.Web.HTTPUtility]::UrlDecode('%1') -replace '^mpv://'); Start-Process -FilePath \\\"D://mpvnet//mpvnet.exe\\\" -ArgumentList $PARAMS}\""

**Comment by LuckyPuppy514** [comment]
是否有第三方杀毒软件，如果有，可以尝试退出后重试
如果可以证明被杀毒软件拦截，一般首次使用会提醒，如果没允许就会导致被拦截，请到恢复区/阻止区之类的地方放行，添加到信任区

**Comment by xwym711** [comment]
将火绒的免打扰模式关闭并重启火绒后，再进行操作火绒会提醒，允许后即可正常使用

**Comment by xwym711** [comment]
上述方法在重启浏览器后仍会出现弹窗，最佳解决办法是 火绒安全软件 -> 安全设置（右上角菜单） -> 系统防护 -> 应用加固，
项目下，加固类型中取消勾选  浏览器。
