### ISSUE TITLE
如何投稿站点？

### ISSUE THREAD

**Issue by hsiayuchih** [LuckyPuppy514/Play-With-MPV#91]
如何投稿站点？

**Comment by LuckyPuppy514** [comment]
提供站点链接，可以加的有空就会添加

**Comment by micro-mieruko** [comment]
> 提供站点链接，可以加的有空就会添加

我是自己用苹果cms搭的视频站点，有没有自己添加的办法。

**Comment by LuckyPuppy514** [comment]
> > 提供站点链接，可以加的有空就会添加
> 
> 我是自己用苹果cms搭的视频站点，有没有自己添加的办法。

自己添加就是自己改代码 😂，每个网站的解析方式都可能不一样，得看具体的网站

**Comment by micro-mieruko** [comment]
> > > 提供站点链接，可以加的有空就会添加
> > 
> > 
> > 我是自己用苹果cms搭的视频站点，有没有自己添加的办法。
> 
> 自己添加就是自己改代码 😂，每个网站的解析方式都可能不一样，得看具体的网站

这样啊，那我把我的视频站开放一下，链接发你看看，https://v.mksec.cn，里面配了3个视频源，分别是量子m3u8，非凡m3u8，xmlm3u8(其实是新浪资源m3u8，配置时名字没写好)，它们链接的域名分别是vip.lz-cdn5.com，vip.ffzy-play6.com，s.xlzys.com。
下面这个视频链接就有3个源，有空的话就麻烦你看一下了😁
https://v.mksec.cn/index.php/vod/detail/id/119605.html

**Comment by LuckyPuppy514** [comment]
> > > > 提供站点链接，可以加的有空就会添加
> > > 
> > > 
> > > 我是自己用苹果cms搭的视频站点，有没有自己添加的办法。
> > 
> > 
> > 自己添加就是自己改代码 😂，每个网站的解析方式都可能不一样，得看具体的网站
> 
> 这样啊，那我把我的视频站开放一下，链接发你看看，[https://v.mksec.cn，里面配了3个视频源，分别是量子m3u8，非凡m3u8，xmlm3u8(其实是新浪资源m3u8，配置时名字没写好)，它们链接的域名分别是vip.lz-cdn5.com，vip.ffzy-play6.com，s.xlzys.com。](https://v.mksec.cn%EF%BC%8C%E9%87%8C%E9%9D%A2%E9%85%8D%E4%BA%863%E4%B8%AA%E8%A7%86%E9%A2%91%E6%BA%90%EF%BC%8C%E5%88%86%E5%88%AB%E6%98%AF%E9%87%8F%E5%AD%90m3u8%EF%BC%8C%E9%9D%9E%E5%87%A1m3u8%EF%BC%8Cxmlm3u8(%E5%85%B6%E5%AE%9E%E6%98%AF%E6%96%B0%E6%B5%AA%E8%B5%84%E6%BA%90m3u8%EF%BC%8C%E9%85%8D%E7%BD%AE%E6%97%B6%E5%90%8D%E5%AD%97%E6%B2%A1%E5%86%99%E5%A5%BD)%EF%BC%8C%E5%AE%83%E4%BB%AC%E9%93%BE%E6%8E%A5%E7%9A%84%E5%9F%9F%E5%90%8D%E5%88%86%E5%88%AB%E6%98%AFvip.lz-cdn5.com%EF%BC%8Cvip.ffzy-play6.com%EF%BC%8Cs.xlzys.com%E3%80%82) 下面这个视频链接就有3个源，有空的话就麻烦你看一下了😁 https://v.mksec.cn/index.php/vod/detail/id/119605.html

[v3.7.7 已添加](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv?version=1226393)

![20230727202150](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/0f993534-6021-49c4-a372-d584b6f3b80f)

**Comment by micro-mieruko** [comment]
> > > > > 提供站点链接，可以加的有空就会添加
> > > > 
> > > > 
> > > > 我是自己用苹果cms搭的视频站点，有没有自己添加的办法。
> > > 
> > > 
> > > 自己添加就是自己改代码 😂，每个网站的解析方式都可能不一样，得看具体的网站
> > 
> > 
> > 这样啊，那我把我的视频站开放一下，链接发你看看，[https://v.mksec.cn，里面配了3个视频源，分别是量子m3u8，非凡m3u8，xmlm3u8(其实是新浪资源m3u8，配置时名字没写好)，它们链接的域名分别是vip.lz-cdn5.com，vip.ffzy-play6.com，s.xlzys.com。](https://v.mksec.cn%EF%BC%8C%E9%87%8C%E9%9D%A2%E9%85%8D%E4%BA%863%E4%B8%AA%E8%A7%86%E9%A2%91%E6%BA%90%EF%BC%8C%E5%88%86%E5%88%AB%E6%98%AF%E9%87%8F%E5%AD%90m3u8%EF%BC%8C%E9%9D%9E%E5%87%A1m3u8%EF%BC%8Cxmlm3u8(%E5%85%B6%E5%AE%9E%E6%98%AF%E6%96%B0%E6%B5%AA%E8%B5%84%E6%BA%90m3u8%EF%BC%8C%E9%85%8D%E7%BD%AE%E6%97%B6%E5%90%8D%E5%AD%97%E6%B2%A1%E5%86%99%E5%A5%BD)%EF%BC%8C%E5%AE%83%E4%BB%AC%E9%93%BE%E6%8E%A5%E7%9A%84%E5%9F%9F%E5%90%8D%E5%88%86%E5%88%AB%E6%98%AFvip.lz-cdn5.com%EF%BC%8Cvip.ffzy-play6.com%EF%BC%8Cs.xlzys.com%E3%80%82) 下面这个视频链接就有3个源，有空的话就麻烦你看一下了😁 https://v.mksec.cn/index.php/vod/detail/id/119605.html
> 
> [v3.7.7 已添加](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv?version=1226393)
> 
> ![20230727202150](https://user-images.githubusercontent.com/53246532/256534421-0f993534-6021-49c4-a372-d584b6f3b80f.gif)

哇！真的太谢谢了！！！

**Comment by micro-mieruko** [comment]
> > > > > 提供站点链接，可以加的有空就会添加
> > > > 
> > > > 
> > > > 我是自己用苹果cms搭的视频站点，有没有自己添加的办法。
> > > 
> > > 
> > > 自己添加就是自己改代码 😂，每个网站的解析方式都可能不一样，得看具体的网站
> > 
> > 
> > 这样啊，那我把我的视频站开放一下，链接发你看看，[https://v.mksec.cn，里面配了3个视频源，分别是量子m3u8，非凡m3u8，xmlm3u8(其实是新浪资源m3u8，配置时名字没写好)，它们链接的域名分别是vip.lz-cdn5.com，vip.ffzy-play6.com，s.xlzys.com。](https://v.mksec.cn%EF%BC%8C%E9%87%8C%E9%9D%A2%E9%85%8D%E4%BA%863%E4%B8%AA%E8%A7%86%E9%A2%91%E6%BA%90%EF%BC%8C%E5%88%86%E5%88%AB%E6%98%AF%E9%87%8F%E5%AD%90m3u8%EF%BC%8C%E9%9D%9E%E5%87%A1m3u8%EF%BC%8Cxmlm3u8(%E5%85%B6%E5%AE%9E%E6%98%AF%E6%96%B0%E6%B5%AA%E8%B5%84%E6%BA%90m3u8%EF%BC%8C%E9%85%8D%E7%BD%AE%E6%97%B6%E5%90%8D%E5%AD%97%E6%B2%A1%E5%86%99%E5%A5%BD)%EF%BC%8C%E5%AE%83%E4%BB%AC%E9%93%BE%E6%8E%A5%E7%9A%84%E5%9F%9F%E5%90%8D%E5%88%86%E5%88%AB%E6%98%AFvip.lz-cdn5.com%EF%BC%8Cvip.ffzy-play6.com%EF%BC%8Cs.xlzys.com%E3%80%82) 下面这个视频链接就有3个源，有空的话就麻烦你看一下了😁 https://v.mksec.cn/index.php/vod/detail/id/119605.html
> 
> [v3.7.7 已添加](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv?version=1226393)
> 
> ![20230727202150](https://user-images.githubusercontent.com/53246532/256534421-0f993534-6021-49c4-a372-d584b6f3b80f.gif)

好像还有点小问题，播放识别出来的m3u8只是一个小片段，不是全段，我去研究下它们是怎么播放的

**Comment by micro-mieruko** [comment]
> > > > > 提供站点链接，可以加的有空就会添加
> > > > 
> > > > 
> > > > 我是自己用苹果cms搭的视频站点，有没有自己添加的办法。
> > > 
> > > 
> > > 自己添加就是自己改代码 😂，每个网站的解析方式都可能不一样，得看具体的网站
> > 
> > 
> > 这样啊，那我把我的视频站开放一下，链接发你看看，[https://v.mksec.cn，里面配了3个视频源，分别是量子m3u8，非凡m3u8，xmlm3u8(其实是新浪资源m3u8，配置时名字没写好)，它们链接的域名分别是vip.lz-cdn5.com，vip.ffzy-play6.com，s.xlzys.com。](https://v.mksec.cn%EF%BC%8C%E9%87%8C%E9%9D%A2%E9%85%8D%E4%BA%863%E4%B8%AA%E8%A7%86%E9%A2%91%E6%BA%90%EF%BC%8C%E5%88%86%E5%88%AB%E6%98%AF%E9%87%8F%E5%AD%90m3u8%EF%BC%8C%E9%9D%9E%E5%87%A1m3u8%EF%BC%8Cxmlm3u8(%E5%85%B6%E5%AE%9E%E6%98%AF%E6%96%B0%E6%B5%AA%E8%B5%84%E6%BA%90m3u8%EF%BC%8C%E9%85%8D%E7%BD%AE%E6%97%B6%E5%90%8D%E5%AD%97%E6%B2%A1%E5%86%99%E5%A5%BD)%EF%BC%8C%E5%AE%83%E4%BB%AC%E9%93%BE%E6%8E%A5%E7%9A%84%E5%9F%9F%E5%90%8D%E5%88%86%E5%88%AB%E6%98%AFvip.lz-cdn5.com%EF%BC%8Cvip.ffzy-play6.com%EF%BC%8Cs.xlzys.com%E3%80%82) 下面这个视频链接就有3个源，有空的话就麻烦你看一下了😁 https://v.mksec.cn/index.php/vod/detail/id/119605.html
> 
> [v3.7.7 已添加](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv?version=1226393)
> 
> ![20230727202150](https://user-images.githubusercontent.com/53246532/256534421-0f993534-6021-49c4-a372-d584b6f3b80f.gif)

没事了，是我mpv播放器的问题，打扰了，还有真的谢谢！！😁

**Comment by micro-mieruko** [comment]
> > > 提供站点链接，可以加的有空就会添加
> > 
> > 
> > 我是自己用苹果cms搭的视频站点，有没有自己添加的办法。
> 
> 自己添加就是自己改代码 😂，每个网站的解析方式都可能不一样，得看具体的网站

不好意思呀老哥，又打扰了。以我视频网站下面的这个视频链接为例子：https://v.mksec.cn/index.php/vod/detail/id/119402.html
量子和非凡的源，播放到第10分钟的时候，会出现“澳门威尼斯人”广告，如果是在mpv中播放到这第10分钟左右的时候，也会出现这广告，但是这时进度条会丢失，进度条会回到最左边，要手动拉回来。（如果不小心拉到第10分钟又会触发广告，进度条回到最左边）
大概是因为广告是新加载的m3u8，不知有办法解决不。🫠

**Comment by LuckyPuppy514** [comment]
不行，只靠这个脚本无法实现

**Comment by micro-mieruko** [comment]
> 不行，只靠这个脚本无法实现

这样啊，那我试试抓包找找广告链接，加入防火墙黑名单。

**Comment by micro-mieruko** [comment]
> > 不行，只靠这个脚本无法实现
> 
> 这样啊，那我试试抓包找找广告链接，加入防火墙黑名单。

只要出现广告，我不按快进，进度条就会回来。就这样吧🥲

**Comment by hsiayuchih** [comment]
> 提供站点链接，可以加的有空就会添加

www.5dm.link

**Comment by LuckyPuppy514** [comment]
> > 提供站点链接，可以加的有空就会添加
> 
> [www.5dm.link](url)

看了下，很多都播放不了，注册还要收费，暂时不添加 😂

**Comment by hsiayuchih** [comment]
> > > 提供站点链接，可以加的有空就会添加
> > 
> > 
> > [www.5dm.link](url)
> 
> 看了下，很多都播放不了，注册还要收费，暂时不添加 😂

啊这，现在注册还要收费了嘛....好吧我注册的早不知道
