### ISSUE TITLE
视频页打不开播放器

### ISSUE THREAD

**Issue by PiscesDreamer** [LuckyPuppy514/Play-With-MPV#92]
- 操作系统： windows10 
- 浏览器： edge 版本 115.0.1901.183（正式版本）（64 位）
- 复现问题的操作： 
- 出现的具体问题：PotPlayer设置好了之后，在视频播放页面调用播放器，出现无法播放的错误。
- 配置截图：
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/81842690/656aa894-2dd4-459c-98cf-e6fc2f3be8ad)

- 报错截图：

![播放错误](https://github.com/LuckyPuppy514/Play-With-MPV/assets/81842690/550c6b2f-e0a2-4285-b288-28779f047040)

**Comment by LuckyPuppy514** [comment]
![20230727181531](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/37fd42c7-c2f6-4f22-88fa-c359b57ec68f)

1. 确保点击保存设置后，点击下载注册表，并双击注册表文件添加注册表；
2. 确保你的 potplayer 是最新版；
3. 确保你的 potplayer 的设置没有问题（上次有人解码方式不行导致无法播放），可以在其他路径重新安装一个试试；

如果以上三点都确认没问题后，还不行，请附上下载的注册表文件

**Comment by PiscesDreamer** [comment]
> ![20230727181531](https://user-images.githubusercontent.com/53246532/256505701-37fd42c7-c2f6-4f22-88fa-c359b57ec68f.jpg)
> 
> 1. 确保点击保存设置后，点击下载注册表，并双击注册表文件添加注册表；
> 2. 确保你的 potplayer 是最新版；
> 3. 确保你的 potplayer 的设置没有问题（上次有人解码方式不行导致无法播放），可以在其他路径重新安装一个试试；
> 
> 如果以上三点都确认没问题后，还不行，请附上下载的注册表文件

必须是最新版的嘛，我用的的版本是老一点的版本，还那个解码方式该设置成那种呢

**Comment by LuckyPuppy514** [comment]
你可以在其他路径安装一个最新版的试试
