### ISSUE TITLE
提供一种第三方网站获取B站弹幕实现MPV外挂弹幕的方法

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [LuckyPuppy514/Play-With-MPV#94]
### **实现效果**
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/62531937/0e40bc28-4b98-4fd5-a345-0d512e32d04f)
(支持 顶部,底部,彩色三种弹幕格式)

### 实现步骤:

1. 在 edge/chrome商店下载**哔哩哔哩助手**插件
[哔哩哔哩助手：bilibili.com 综合辅助扩展-edge](https://microsoftedge.microsoft.com/addons/detail/%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E5%8A%A9%E6%89%8B%EF%BC%9Abilibilicom-%E7%BB%BC%E5%90%88%E8%BE%85%E5%8A%A9%E6%89%A9/fcfebhekhbkhjjimonjmbgmkbclheaoh)
 [哔哩哔哩助手：bilibili.com 综合辅助扩展-chrome](https://chrome.google.com/webstore/detail/%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E5%8A%A9%E6%89%8B%EF%BC%9Abilibilicom-%E7%BB%BC%E5%90%88%E8%BE%85%E5%8A%A9%E6%89%A9%E5%B1%95/kpbnombpnpcffllnianjibmpadjolanh?hl=zh-CN)

2. 进入任意B站视频界面
此处以港澳台番剧 鬼灭之刃刀匠村篇 第一集为(请开全局代理和解锁番剧插件)例

**点击粉色小猫,并点击下载弹幕**
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/62531937/a5e361e0-883f-4e02-a26e-929b99aed555)

点击 保存为 ASS格式
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/62531937/70dbf666-f6d1-4088-a76e-317c990ea4a9)

3. 在其他网站正常加载视频
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/62531937/3fb90d8e-4426-4812-9276-b4e803742b66)

4. 加载成功后在播放器中点击**其他字幕**
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/62531937/5b8f7290-9939-4cd1-8579-f8c1b8665e60)

5. 正常播放

### **改进:**
在保存字幕文件时通过js脚本将'文件名+路径'复杂到剪贴板,并让播放器自动检测剪贴板中的文件

### **参考视频**
[如何在本地播放器加载B站弹幕进行视频观看](https://www.bilibili.com/video/BV1DY411w7LT/?spm_id_from=333.337.top_right_bar_window_default_collection.content.click&vd_source=55ef7ba465c1a49045746c4eada07700)

### **缺点:**
![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/62531937/97bdb544-5bf4-4402-815e-bb17cfd884d0)
如图,无法完全获取B站弹幕
这是由于插件内已经默认了弹幕获取延时的数值,我猜测这一设置决定了同时发送的弹幕或者其发送时间差小于某一数值的弹幕无法被检测到

### **解决方法**
如果图片中两处弹幕差过大,可以通过

- 手动扒取B站弹幕

- BiliTool/BiliPlus(网站服务器有些慢) [哔哩哔哩最新获取全弹幕方式（全教程）](https://www.bilibili.com/video/BV1z3411y7uX/?share_source=copy_web&vd_source=c4903f7fdf358ee4ab0d376ba6c05740)通过之前说的插件提供cid搜索弹幕,调整最小/最小延时获取弹幕XML文件,并用[XML2ASS程序](NaiboWang/Bilibili-XMLSubtitle-to-ASS)转为字幕

![image](https://github.com/LuckyPuppy514/Play-With-MPV/assets/62531937/5570f686-8cf2-4d15-ac25-79610340fce2)

最小延时2s多获取到两条弹幕

**Comment by LuckyPuppy514** [comment]
也可以看下 [弹弹Play](https://www.dandanplay.com/) 和 [KikoPlay](https://github.com/KikoPlayProject/KikoPlay)

**Comment by systemoutprintlnhelloworld** [comment]
> 也可以看下 [弹弹Play](https://www.dandanplay.com/) 和 [KikoPlay](https://github.com/KikoPlayProject/KikoPlay)

感谢回复,我是弹弹那边过来的,因为弹弹play播放器不支持在播放网站上的流视频时调用其他播放器,只支持播放本地视频时调用

**Comment by systemoutprintlnhelloworld** [comment]
目前 hd2a改版,无法看到该插件,biliplus同样支持该功能,复制bv号即可
