### ISSUE TITLE
如何自行调用mpv播放到自己指定的网站？

### ISSUE THREAD

**Issue by hkiceflow** [LuckyPuppy514/Play-With-MPV#95]
我将自己的nas挂载到公网上，那我该如何在emby中调用出mpv？
handler总是显示获取不到token

**Comment by LuckyPuppy514** [comment]
不建议使用脚本，建议使用客户端，很完善了，还能同步播放时间
可以到我博客下载：https://kutt.lckp.top/jOPDvh
