### ISSUE TITLE
能否实现链接右键菜单中加入Play with mpv

### ISSUE THREAD

**Issue by dupontjoy** [LuckyPuppy514/Play-With-MPV#96]
能否实现链接右键菜单中加入Play with mpv，点击后直接调用mpv播放此链接？
目前需要视频页面，不是很方便

**Comment by LuckyPuppy514** [comment]
暂时不行，基本上都是要根据视频页的信息获取播放链接的

**Comment by LuckyPuppy514** [comment]
如果是可以直接播放的，倒是还行，但是暂时不考虑，其实直接播放的，你复制粘贴到播放器也能播放 😂

**Comment by dupontjoy** [comment]
> 如果是可以直接播放的，倒是还行，但是暂时不考虑，其实直接播放的，你复制粘贴到播放器也能播放 😂

明白了
就是想再偷点懒，不打开页面嘛😂

**Comment by LuckyPuppy514** [comment]
> > 如果是可以直接播放的，倒是还行，但是暂时不考虑，其实直接播放的，你复制粘贴到播放器也能播放 😂
> 
> 明白了 就是想再偷点懒，不打开页面嘛😂

想偷懒就在设置里面开启自动播放，点击进入页面了会自动打开 mpv 播放
