### ISSUE TITLE
合并细分单独控制单一路径启动播放器

### ISSUE THREAD

**Issue by IM515BT** [LuckyPuppy514/Play-With-MPV#97]
- 操作系统： windows10/
- 提个建议：
是否可以复现：左下角的点击按钮在**_设置_**里面已经有三个设置路径，然后把这个三个路径合并到左下角的圆形按钮（呈现三角分割等分分布），点击那边就单独启动那边的播放器----觉得每次要换个播放器都要重新下载注册表有点不便。

**Comment by LuckyPuppy514** [comment]
[v3.8.8 已添加](https://greasyfork.org/zh-CN/scripts/444056-play-with-mpv?version=1244402)

![20230902154740](https://github.com/LuckyPuppy514/Play-With-MPV/assets/53246532/fdb2d1fc-fc18-4512-8aee-9b08f552259e)

**Comment by IM515BT** [comment]
ok,用上了。好用的
