### ISSUE TITLE
Cannot play Twitch videos

### ISSUE THREAD

**Issue by showgood163** [LuckyPuppy514/Play-With-MPV#99]
windows 10, chromium 116.0.5845.82

script version 3.8.3

Cannot play any Twitch videos, reports "no file" error

**Comment by LuckyPuppy514** [comment]
some websites such as youtube, twitch depend on yt-dlp, please update to the latest version from below and try again
[https://github.com/yt-dlp/yt-dlp/releases](https://github.com/yt-dlp/yt-dlp/releases)

**Comment by showgood163** [comment]
Sorry. After some debugging I found that the script is working correctly.
